'use strict';
/* ============================================================
   铭刻前线 —— 卡牌数据层（src/cards.js）
铭刻前线 —— 卡牌数据层（src/cards.js）
   数据唯一基准：铭刻前线.v1.html.bak（现有 HTML 修复后版本）。
   注意：数值/字段以 HTML 为准，不是以《文档.txt》为准。
   本文件允许使用 DOM API（drawSprite 接收 canvas），但自身
   不引用 document/window 全局（除 canvas 参数外）。
   ============================================================ */

/* ---------- 词条 / 类型 ---------- */
const SIGINFO = {
  blitz:  {n:'闪击', d:'推进后仍可攻击'},
  guard:  {n:'守护', d:'地面单位必须优先攻击它（炮兵/轰炸机/战斗机可绕过）'},
  ambush: {n:'伏击', d:'每回合首次被攻击时先反击'},
  smoke:  {n:'烟幕', d:'无法被攻击；移动或攻击后失去'},
  fight:  {n:'奋战', d:'一回合可攻击两次'},
  impact: {n:'冲击', d:'首次攻击时被攻击单位不会造成任何反击伤害；攻击单位后移除冲击'},
  veteran:{n:'老兵', d:'满足卡面条件后升为老兵；老兵形态与本体是同一张卡'},
  coop:   {n:'协力', d:'使用该卡牌时，除非回合开始时场上有相同国家的友方单位，否则总部受到 1 点士气伤害（无法减免）'},
  情报1:  {n:'情报1', d:'使用时：随机显示敌方 1 张手牌'}
};
const TYPEINFO = { infantry:'步兵', tank:'坦克', artillery:'炮兵', fighter:'战斗机', bomber:'轰炸机' };

/* ---------- 卡牌数据（来自 HTML 基准版） ---------- */
const R = '卡牌/';
/* 单位卡：{n:名称, t:类型, c:部署花费(血液), f:油费, a:攻击, h:血量, s:词条[], r:重甲, e:效果, d:部署效果} */
const NATIONS = {
  us: { name:'美国', hq:'装饰/总部/美/瑟堡.png',
    units:[
      {id:'b17', n:'B-17飞行堡垒', t:'bomber', c:8, f:3, a:5, h:5, r:1, d:'elimRand'},
      {id:'p51', n:'P-51野马', t:'fighter', c:6, f:2, a:6, h:4, d:'dmgFlyRand5'},
      {id:'p40', n:'P-40战鹰', t:'fighter', c:3, f:2, a:2, h:3, e:['vsArmy3','vsHq3']},
      {id:'m7', n:'M7牧师', t:'artillery', c:3, f:1, a:2, h:2, d:'frontAlly11'},
      {id:'f4u', n:'F4U-1C海盗', t:'fighter', c:5, f:2, a:4, h:6},
      {id:'b25', n:'B-25米切尔', t:'bomber', c:6, f:3, a:4, h:5, d:'dmgRand3'},
      {id:'m18', n:'M18地狱猫', t:'tank', c:3, f:1, a:4, h:2, s:['blitz'], e:['vsTank2x']},
      {id:'sbd', n:'SBD 3 无畏', t:'bomber', c:3, f:2, a:3, h:3, r:1},
      {id:'r17', n:'第17步兵团', t:'infantry', c:2, f:1, a:2, h:2, d:'ally11', target:'friendly'},
      {id:'r506', n:'第506空降步兵团', t:'infantry', c:1, f:1, a:2, h:2},
      {id:'t19', n:'T19 榴弹炮', t:'artillery', c:2, f:1, a:1, h:3, e:['t19GuardBreak'], img:R+'美/T19 榴弹炮.jpg'},
      {id:'r104', n:'第104步兵团', t:'infantry', c:4, f:1, a:6, h:6, s:['smoke'], img:R+'美/第104步兵团.jpg'},
      {id:'f4f', n:'F4F-4 野猫', t:'fighter', c:2, f:2, a:2, h:3, s:['blitz'], e:['f4fBuff'], img:R+'美/F4F-4 野猫.jpg'},
      {id:'pb2y', n:'PB2Y卡罗纳多', t:'bomber', c:4, f:2, a:2, h:4, e:['pb2yAura','drawReveal'], img:R+'美/PB2Y卡罗纳多.jpg'},
      {id:'r32', n:'第32步兵团', t:'infantry', c:1, f:1, a:2, h:1, d:'r32Copy', img:R+'美/第32步兵团.png'},
      {id:'r1def', n:'第1防卫营', t:'infantry', c:1, f:0, a:1, h:2, s:['blitz','coop'], d:'r1defBuff', img:R+'美/第1防卫营.png'},
      {id:'reddevil', n:'红魔空降步兵团', t:'infantry', c:1, f:1, a:1, h:3, s:['blitz'], e:['reddevil'], img:R+'美/红魔空降步兵团.png'},
      {id:'r164', n:'第164步兵团', t:'infantry', c:1, f:0, a:1, h:1, s:['blitz'], e:['r164Death'], img:R+'美/第164步兵团.png'},
      {id:'eng109', n:'第109战斗工兵营', t:'infantry', c:1, f:1, a:1, h:2, s:['smoke'], e:['eng109'], img:R+'美/第109战斗工兵营.png'},
      {id:'comm593', n:'第593联合通信连', t:'infantry', c:1, f:4, a:0, h:4, s:['smoke'], e:['hqDmgReduce1'], img:R+'美/第593联合通信连.png'},
      {id:'M26潘兴', n:'M26潘兴', c:10, t:'tank', f:3, a:8, h:8, s:['blitz'], r:2, d:'M26潘兴'},
      {id:'第142步兵团', n:'第142步兵团', c:2, t:'infantry', f:1, a:2, h:3, s:['blitz'], d:'第142步兵团'},
      {id:'第5步兵团', n:'第5步兵团', c:2, t:'infantry', f:1, a:2, h:3, d:'第5步兵团'},
      {id:'霹雳师', n:'霹雳师', c:3, t:'infantry', f:1, a:3, h:5, s:['smoke','impact'], d:'霹雳师'},
      {id:'第175步兵团', n:'第175步兵团', c:3, t:'infantry', f:1, a:6, h:6, s:['blitz'], d:'第175步兵团'},
      {id:'红牛师', n:'红牛师', c:3, t:'infantry', f:1, a:1, h:6, d:'红牛师'},
      {id:'M10A1', n:'M10A1', c:3, t:'tank', f:1, a:4, h:2, d:'M10A1'},
      {id:'F7F虎猫', n:'F7F虎猫', c:6, t:'fighter', f:2, a:5, h:5, d:'F7F虎猫'},
      {id:'M6', n:'M6', c:7, t:'tank', f:3, a:7, h:7, r:2, d:'M6'},
      {id:'超级堡垒B-29', n:'超级堡垒B-29', c:12, t:'bomber', f:4, a:9, h:9, s:['blitz'], r:2, d:'超级堡垒B-29'},
    ],
    orders:[
      {id:'gunboat', n:'炮艇任务', c:2, e:'gunboat', target:'enemy-backline'},
      {id:'deathfromabove', n:'死神降临', c:4, e:'deathFromAbove'},
      {id:'warmachine', n:'战争机器', c:2, e:'warMachine'},
      {id:'missouri', n:'USS密苏里号', c:3, e:'missouri', target:'enemy-frontline', img:R+'美/USS密苏里号.jpg'},
      {id:'usarmyair', n:'美国陆军航空队', c:2, e:'usArmyAir', img:R+'美/美国陆军航空队.jpg'},
      {id:'warneed', n:'战争需要', c:4, e:'warNeed', img:R+'美/战争需要.jpg'},
      {id:'warbond', n:'战争债券', c:5, e:'warBond', img:R+'美/战争债券.jpg'},
      {id:'aswpatrol', n:'反潜巡逻', c:7, e:'aswPatrol', img:R+'美/反潜巡逻.jpg'},
      {id:'aircover', n:'空中掩护', c:3, e:'airCover', img:R+'美/空中掩护.jpg'},
      {id:'carriergroup', n:'航母打击群', c:3, e:'carrierGroup', img:R+'美/航母打击群.jpg'},
      {id:'carriercover', n:'航母掩护', c:1, e:'carrierCover', img:R+'美/航母掩护.jpg'},
      {id:'yorktown', n:'USS约克城号', c:5, e:'yorktown', img:R+'美/USS约克城号.jpg'},
      {id:'patton', n:'巴顿', c:1, e:'patton', img:R+'美/巴顿.png'},
      {id:'forfreedom', n:'为了自由', c:1, e:'forFreedom', target:'friendly-unit', img:R+'美/为了自由.png'},
      {id:'quinine', n:'奎宁', c:1, e:'quinine', target:'friendly-infantry', img:R+'美/奎宁.png'},
      {id:'motivate', n:'激励部队', c:4, e:'motivate', target:'friendly-unit', img:R+'美/激励部队.png'},
      {id:'stratbomb', n:'战略轰炸', c:6, e:'stratBomb', img:R+'美/战略轰炸.jpg'},
      {id:'airdrop', n:'伞降突袭', c:4, e:'paraDrop', img:R+'美/伞降突袭.jpg'},
      {id:'coerce', n:'胁迫', c:0, e:'coerce', target:'any', img:R+'美/胁迫.png'},
      {id:'nightbomb', n:'夜间轰炸', c:5, e:'nightBomb', target:'any', img:R+'美/夜间轰炸.png'},
      {id:'highbomb', n:'高空轰炸', c:8, e:'highBomb', img:R+'美/高空轰炸.png'},
      {id:'陆军工程兵团', n:'陆军工程兵团', c:0, e:'陆军工程兵团', target:'any'},
      {id:'战略规划', n:'战略规划', c:10, e:'战略规划'},
      {id:'消耗战', n:'消耗战', c:2, e:'消耗战', target:'any'},
      {id:'防火墙', n:'防火墙', c:2, e:'防火墙', target:'any'},
      {id:'黑夜巡视', n:'黑夜巡视', c:2, e:'黑夜巡视'},
      {id:'战时美利坚', n:'战时美利坚', c:3, e:'战时美利坚'},
      {id:'星条旗', n:'星条旗', c:5, e:'星条旗'},
      {id:'我们能做到！', n:'我们能做到！', c:5, e:'我们能做到！'},
      {id:'同盟国', n:'同盟国', c:5, e:'同盟国'},
      {id:'掩护部队', n:'掩护部队', c:7, e:'掩护部队'},
      {id:'爱国热忱', n:'爱国热忱', c:7, e:'爱国热忱', target:'friendly-unit'},
      {id:'美国军事研发', n:'美国军事研发', c:3, e:'美国军事研发'},
    ],
    counters:[
      {id:'spot', n:'发现敌人', c:1, e:'spotEnemy'}
    ] },
  de: { name:'德国', hq:'装饰/总部/德/但泽.png',
    units:[
      {id:'leopold', n:'利奥波德', t:'artillery', c:10, f:3, a:6, h:4, d:'enemiesBack'},
      {id:'pz2', n:'二号坦克A型', t:'tank', c:1, f:1, a:1, h:3, s:['blitz','smoke']},
      {id:'pz35', n:'35（t）坦克', t:'tank', c:2, f:1, a:2, h:2, s:['blitz'], d:'allyInfantryOil'},
      {id:'r59', n:'第59装甲掷弹兵团', t:'infantry', c:2, f:1, a:3, h:3, e:['moveNattack'], img:R+'德/第59装甲掷弹兵团.png'},
      {id:'bf109', n:'BF 109 E', t:'fighter', c:3, f:2, a:3, h:4},
      {id:'tiger', n:'虎式坦克H型', t:'tank', c:8, f:3, a:8, h:8, r:2, e:['immuneSuppress']},
      {id:'r980', n:'第980国民掷弹兵团', t:'infantry', c:3, f:1, a:3, h:6},
      {id:'panzer3', n:'豹式坦克A型 防磁装甲型', t:'tank', c:3, f:0, a:2, h:3, s:['blitz'], e:['panzer'], img:R+'德/豹式坦克A型 防磁装甲型.jpg'},
      {id:'pz3j', n:'三号坦克J型', t:'tank', c:4, f:2, a:4, h:5, s:['blitz'], img:R+'德/三号坦克J型.jpg'},
      {id:'r20', n:'第20装甲掷弹兵团', t:'infantry', c:5, f:1, a:3, h:4, s:['blitz'], d:'r20Add', img:R+'德/第20装甲掷弹兵团.png'},
      {id:'hs129', n:'Hs 129', t:'fighter', c:5, f:2, a:4, h:5, e:['hs129Atk'], d:'hs129Fight', target:'enemy', img:R+'德/Hs 129.png'},
      {id:'r7', n:'第7步枪兵团', t:'infantry', c:4, f:1, a:4, h:5, s:['blitz'], e:['r7Vet'], img:R+'德/第7步枪兵团.png'},
      {id:'me163', n:'Me 163彗星', t:'fighter', c:6, f:0, a:4, h:2, s:['blitz'], e:['me163Back'], img:R+'德/Me 163彗星.jpg'},
      {id:'me262', n:'Me 262 A飞燕', t:'fighter', c:9, f:3, a:7, h:5, d:'me262Clear', img:R+'德/Me 262 A飞燕.jpg'},
      {id:'ktiger', n:'虎王坦克II型', t:'tank', c:12, f:4, a:9, h:9, r:2, d:'ktigerCrush'},
      {id:'gryphon', n:'狮鹫指挥车', t:'tank', c:1, f:1, a:1, h:1, e:['gryphon'], img:R+'德/狮鹫指挥车.png'},
      {id:'pantherD', n:'豹式坦克D型', t:'tank', c:7, f:3, a:7, h:6, r:1, e:['pantherD'], img:R+'德/豹式坦克D型.png'},
      {id:'rhodes', n:'罗得突击旅', t:'infantry', c:7, f:1, a:7, h:7, e:['rhodesCost'], img:R+'德/罗得突击旅.png'},
      {id:'tigerE', n:'虎式坦克E型', t:'tank', c:8, f:3, a:7, h:7, r:2, e:['tigerE'], img:R+'德/虎式坦克E型.png'},
      {id:'bp42', n:'BP-42装甲列车', t:'tank', c:9, f:5, a:5, h:9, r:1, d:'bp42', img:R+'德/BP-42装甲列车.png'},
      {id:'虎王', n:'虎王', c:12, t:'tank', f:4, a:10, h:10, r:2, d:'虎王'},
      {id:'鼠式', n:'鼠式', c:12, t:'tank', f:4, a:12, h:10, r:3, d:'鼠式'},
      {id:'第158补给营', n:'第158补给营', c:1, t:'infantry', f:4, a:0, h:4, s:['smoke'], d:'第158补给营'},
      {id:'三号坦克L型', n:'三号坦克L型', c:3, t:'tank', f:2, a:3, h:5, s:['blitz'], d:'三号坦克L型'},
      {id:'38(t)坦克', n:'38(t)坦克', c:3, t:'tank', f:1, a:2, h:3, d:'38(t)坦克'},
      {id:'三号坦克H型', n:'三号坦克H型', c:4, t:'tank', f:1, a:2, h:4, d:'三号坦克H型'},
      {id:'豹式坦克A型', n:'豹式坦克A型', c:5, t:'tank', f:2, a:5, h:5, r:1, d:'豹式坦克A型', e:['pantherA']},
      {id:'第119掷弹兵团', n:'第119掷弹兵团', c:6, t:'infantry', f:2, a:6, h:6, s:['fight'], d:'第119掷弹兵团'},
      {id:'第35掷弹兵团', n:'第35掷弹兵团', c:6, t:'infantry', f:2, a:6, h:6, s:['blitz'], d:'第35掷弹兵团'},
      {id:'Fw190A百舌鸟', n:'Fw190A百舌鸟', c:6, t:'fighter', f:2, a:5, h:5, d:'Fw190A百舌鸟'},
      {id:'四号坦克H型', n:'四号坦克H型', c:7, t:'tank', f:2, a:5, h:5, d:'四号坦克H型'},
    ],
    orders:[
      {id:'eagleclaw', n:'鹰爪', c:3, e:'eagleClaw'},
      {id:'airstrike', n:'空中闪击', c:3, e:'airStrike'},
      {id:'bismarck', n:'KM 俾斯麦号', c:10, e:'bismarck'},
      {id:'tirpitz', n:'KM提尔皮茨号', c:5, e:'tirpitz', img:R+'德/KM提尔皮茨号.jpg'},
      {id:'blitzkrieg', n:'闪电战', c:3, e:'blitzKrieg', img:R+'德/闪电战.png'},
      {id:'coopop', n:'协同作战', c:1, e:'coopOp', target:'friendly-tank', img:R+'德/协同作战.png'},
      {id:'bridge', n:'遥远的桥', c:5, e:'bridgeTooFar', img:R+'德/遥远的桥.jpg'},
      {id:'enigma', n:'恩尼格玛', c:4, e:'enigma', img:R+'德/恩尼格玛.jpg'},
      {id:'buzzbomb', n:'嗡嗡炸弹', c:1, e:'buzzBomb', target:'enemy-unit', img:R+'德/嗡嗡炸弹.jpg'},
      {id:'warnavy', n:'战争海军', c:7, e:'warNavy', img:R+'德/战争海军.jpg'},
      {id:'wolfpack', n:'狼群战术', c:4, e:'wolfPack', target:'any', img:R+'德/狼群战术.jpg'},
      {id:'wedge', n:'装甲楔形阵', c:1, e:'armorWedge', target:'friendly-tank', img:R+'德/装甲楔形阵.jpg'},
      {id:'ironore', n:'北方铁矿', c:1, e:'ironOre', img:R+'德/北方铁矿.png'},
      {id:'guderian', n:'古德里安', c:1, e:'guderian', img:R+'德/古德里安.png'},
      {id:'routcheap', n:'溃敌', c:1, e:'routCheap', target:'any', img:R+'德/溃敌.png'},
      {id:'inhibit', n:'抑制', c:1, e:'inhibitOne', target:'any', img:R+'德/抑制.png'},
      {id:'exploit', n:'扩大优势', c:6, e:'exploitGain', img:R+'德/扩大优势.png'},
      {id:'alpine', n:'阿尔卑斯要塞', c:7, e:'alpineFort', img:R+'德/阿尔卑斯要塞.png'},
      {id:'massrout', n:'一触即溃', c:8, e:'massRout', img:R+'德/一触即溃.png'},
      {id:'俯冲轰炸', n:'俯冲轰炸', c:1, e:'俯冲轰炸', target:'enemy-unit'},
      {id:'转变攻击', n:'转变攻击', c:2, e:'转变攻击', target:'friendly-unit'},
      {id:'第二战线', n:'第二战线', c:4, e:'第二战线', target:'friendly-unit'},
      {id:'交叉火力', n:'交叉火力', c:4, e:'交叉火力'},
      {id:'斩草除根', n:'斩草除根', c:4, e:'斩草除根'},
      {id:'大混战', n:'大混战', c:8, e:'大混战'},
      {id:'德意志帝国研发', n:'德意志帝国研发', c:3, e:'德意志帝国研发'},
    ],
    counters:[
      {id:'smalltalk', n:'无心漫谈', c:1, e:'enemyDeployDmg'},
      {id:'flashraid', n:'闪电袭击', c:1, e:'enemyDrawPunish', img:R+'德/闪电袭击.jpg'},
      {id:'fromdeep', n:'来自深处', c:2, e:'fromDeep', img:R+'德/来自深处.png'}
    ] },
  su: { name:'苏联', hq:'装饰/总部/苏/斯大林格勒.png',
    units:[
      {id:'r84', n:'步兵第84团', t:'infantry', c:3, f:1, a:1, h:8, s:['guard']},
      {id:'i16', n:'伊-16 毛驴', t:'fighter', c:2, f:1, a:2, h:2},
      {id:'r554', n:'步兵第554团', t:'infantry', c:0, f:0, a:1, h:1, s:['blitz']},
      {id:'r89', n:'步兵第89团', t:'infantry', c:1, f:1, a:1, h:3, s:['guard']},
      {id:'t34', n:'T-34 1942', t:'tank', c:5, f:2, a:5, h:5, s:['blitz']},
      {id:'t70', n:'T-70', t:'tank', c:2, f:1, a:3, h:2, s:['guard']},
      {id:'su76', n:'SU-76M', t:'tank', c:3, f:1, a:5, h:4, d:'hqDmg2'},
      {id:'katyusha', n:'喀秋沙', t:'artillery', c:2, f:1, a:1, h:2, s:['blitz'], e:['chanceExtra1']},
      {id:'il28', n:'伊尔-28M', t:'bomber', c:4, f:2, a:4, h:3, r:1, e:['overflowHq']},
      {id:'yak9', n:'雅克-9', t:'fighter', c:5, f:2, a:4, h:5, e:['deathDraw']},
      {id:'partisan', n:'布良斯克游击队', t:'infantry', c:2, f:1, a:0, h:6, s:['guard'], e:['partisan'], img:R+'苏/布良斯克游击队.jpg'},
      {id:'r216', n:'近卫步兵第216团', t:'infantry', c:3, f:1, a:3, h:5, e:['guard216'], img:R+'苏/近卫步兵第216团.jpg'},
      {id:'t3485', n:'T-34-85 1945', t:'tank', c:6, f:2, a:6, h:6, s:['blitz','impact'], r:1, e:['inhibitImmune','keepImpact'], img:R+'苏/T-34-85 1945.jpg'},
      {id:'m503', n:'摩托化步兵第503团', t:'infantry', c:3, f:1, a:2, h:5, s:['guard'], d:'m503Buff', img:R+'苏/摩托化步兵第503团.jpg'},
      {id:'r25', n:'步兵第25团', t:'infantry', c:8, f:2, a:6, h:7, s:['guard'], e:['r25Spawn'], img:R+'苏/步兵第25团.jpg'},
      {id:'stz', n:'STZ-5喀秋莎', t:'artillery', c:3, f:0, a:1, h:2, s:['blitz'], e:['stzGen'], img:R+'苏/STZ-5喀秋莎.png'},
      {id:'r75', n:'步兵第75团', t:'infantry', c:6, f:2, a:6, h:7, s:['guard'], e:['r75Copy'], img:R+'苏/步兵第75团.png'},
      {id:'eng329', n:'工兵第329营', t:'infantry', c:1, f:4, a:0, h:4, s:['smoke'], e:['eng329'], img:R+'苏/工兵第329营.png'},
      {id:'holm99', n:'霍尔姆第99团', t:'infantry', c:1, f:0, a:2, h:3, s:['blitz'], d:'holm99', img:R+'苏/霍尔姆第99团.png'},
      {id:'p39', n:'P-39 小蛇', t:'fighter', c:3, f:2, a:4, h:5, s:['blitz'], d:'p39', img:R+'苏/P-39 小蛇.png'},
      {id:'IS-2', n:'IS-2', c:10, t:'tank', f:1, a:8, h:8, r:2, d:'IS-2'},
      {id:'近卫机械化第12旅', n:'近卫机械化第12旅', c:1, t:'infantry', f:1, a:2, h:1, s:['smoke'], d:'近卫机械化第12旅'},
      {id:'伊尔-10', n:'伊尔-10', c:3, t:'fighter', f:1, a:4, h:3, d:'伊尔-10'},
      {id:'SU-85', n:'SU-85', c:4, t:'tank', f:1, a:5, h:3, d:'SU-85'},
      {id:'BP-43装甲列车', n:'BP-43装甲列车', c:5, t:'tank', f:5, a:3, h:7, s:['guard'], r:1, d:'BP-43装甲列车'},
      {id:'近卫步兵第4团', n:'近卫步兵第4团', c:9, t:'infantry', f:2, a:9, h:9, s:['guard'], d:'近卫步兵第4团'},
    ],
    /* 近卫步兵第216团·老兵形态（供引擎就地转换的模板；非独立卡：不进卡池/不占池位，与本体是同一张卡）
       {n:'近卫步兵第216团（老兵）', t:'infantry', c:3, f:1, a:3, h:6, s:['veteran','guard']}, img:'卡牌/苏/近卫步兵第216团（老兵）.jpg' */
    orders:[
      {id:'burningsky', n:'燃烧的天空', c:1, e:'burningSky', target:'enemy-fly'},
      {id:'frompeople', n:'来自人民', c:3, e:'fromPeople', target:'enemy-unit'},
      {id:'winterwar', n:'冬季战争', c:1, e:'winterWar'},
      {id:'bloodsickle', n:'血红镰刀', c:1, e:'bloodSickle', target:'enemy-unit'},
      {id:'gw', n:'伟大的卫国战争', c:6, e:'greatWar'},
      {id:'winteroff', n:'冬季攻势', c:7, e:'winterOffensive'},
      {id:'mudseason', n:'泥泞季', c:2, e:'mudSeason', img:R+'苏/泥泞季.jpg'},
      {id:'hammer', n:'铁锤', c:3, e:'hammer', target:'enemy-army', img:R+'苏/铁锤.jpg'},
      {id:'focus', n:'战略重心', c:7, e:'strategicFocus', img:R+'苏/战略重心.jpg'},
      {id:'reserve', n:'预备役', c:1, e:'reserve', img:R+'苏/预备役.jpg'},
      {id:'deepop', n:'大纵深作战', c:2, e:'deepOp', img:R+'苏/大纵深作战.jpg'},
      {id:'frontalassault', n:'正面突击', c:2, e:'frontalAssault', img:R+'苏/正面突击.jpg'},
      {id:'roadberlin', n:'柏林之路', c:1, e:'roadBerlin', img:R+'苏/柏林之路.png'},
      {id:'zhukov', n:'朱可夫', c:1, e:'zhukov', img:R+'苏/朱可夫.png'},
      {id:'closecombat', n:'短兵相接', c:2, e:'closeCombat', img:R+'苏/短兵相接.png'},
      {id:'weigh', n:'权衡', c:2, e:'weighOptions', img:R+'苏/权衡.png'},
      {id:'harshwinter', n:'严冬', c:5, e:'harshWinter', img:R+'苏/严冬.png'},
      {id:'tractorplant', n:'拖拉机厂', c:8, e:'tractorPlant', img:R+'苏/拖拉机厂.png'},
      {id:'frontarmy', n:'方面军', c:9, e:'frontArmy', img:R+'苏/方面军.png'},
      {id:'背水一战', n:'背水一战', c:0, e:'背水一战', target:'any'},
      {id:'最后一击', n:'最后一击', c:1, e:'最后一击', target:'friendly-unit'},
      {id:'暴风雪', n:'暴风雪', c:1, e:'暴风雪'},
      {id:'焦土政策', n:'焦土政策', c:2, e:'焦土政策'},
      {id:'以剑之名', n:'以剑之名', c:4, e:'以剑之名'},
      {id:'胜利旗帜', n:'胜利旗帜', c:7, e:'胜利旗帜', target:'any'},
      {id:'苏联军事研发', n:'苏联军事研发', c:3, e:'苏联军事研发'},
    ],
    counters:[] },
  gb: { name:'英国', hq:'装饰/总部/英/亚历山大港.png',
    units:[
      {id:'westaf', n:'第2西非旅', t:'infantry', c:1, f:1, a:1, h:2, d:'wafrica', img:R+'英/第2西非旅.jpg'},
      {id:'ucarrier', n:'通用载具', t:'tank', c:1, f:1, a:1, h:2, s:['smoke'], e:['ucarrierAura'], img:R+'英/通用载具.jpg'},
      {id:'middlesex', n:'米德尔赛克斯团', t:'infantry', c:1, f:1, a:1, h:3, s:['guard'], d:'middlesexAdd', img:R+'英/米德尔赛克斯团.jpg'},
      {id:'cmdo9', n:'第9突击队', t:'infantry', c:1, f:1, a:1, h:1, d:'def1Pick', target:'enemy-unit', img:R+'英/第9突击队.jpg'},
      {id:'charmboy', n:'魅力男孩高地人团', t:'infantry', c:5, f:1, a:3, h:6, s:['guard'], d:'charmHq', img:R+'英/魅力男孩高地人团.jpg'},
      {id:'cmdo46', n:'第46突击队', t:'infantry', c:1, f:1, a:1, h:1, d:'cmdo46Add', img:R+'英/第46突击队.jpg'},
      {id:'r5', n:'第5步兵旅', t:'infantry', c:2, f:1, a:1, h:5, s:['guard']},
      {id:'humber', n:'亨伯 MKII', t:'tank', c:1, f:1, a:1, h:3, s:['fight']},
      {id:'churchill', n:'丘吉尔Mk VI', t:'tank', c:5, f:2, a:2, h:7, s:['guard'], r:1},
      {id:'lancaster', n:'兰卡斯特Mk I', t:'bomber', c:8, f:3, a:7, h:4, s:['blitz']},
      {id:'swordfish', n:'剑鱼 MKI', t:'bomber', c:1, f:1, a:1, h:3},
      {id:'spitfire', n:'喷火Mk la', t:'fighter', c:5, f:2, a:5, h:5},
      {id:'coldstream', n:'冷溪卫队', t:'infantry', c:3, f:1, a:1, h:4, s:['guard'], d:'coldstream', img:R+'英/冷溪卫队.jpg'},
      {id:'lancashire', n:'兰开夏燧发枪兵团', t:'infantry', c:4, f:1, a:5, h:6, img:R+'英/兰开夏燧发枪兵团.jpg'},
      {id:'cameron', n:'女王直属卡梅伦高地人团', t:'infantry', c:7, f:2, a:7, h:7, s:['blitz','fight'], d:'bounceTop', target:'enemy-unit', img:R+'英/女王直属卡梅伦高地人团.jpg'},
      {id:'manchester', n:'曼彻斯特 Mk Ia', t:'bomber', c:7, f:3, a:6, h:4, d:'manchesterPrec', img:R+'英/曼彻斯特 Mk Ia.jpg'},
      {id:'stirling', n:'斯特林 MK III', t:'bomber', c:6, f:2, a:5, h:5, s:['blitz'], d:'stirlingCarpet', img:R+'英/斯特林 MK III.png'},
      {id:'avre', n:'丘吉尔 MKIII AVRE', t:'tank', c:7, f:2, a:5, h:7, r:1, d:'avreRetreat', img:R+'英/丘吉尔 MKIII AVRE.jpg'},
      {id:'meteor', n:'流星', t:'fighter', c:4, f:1, a:1, h:1, s:['blitz'], e:['meteorAfter'], img:R+'英/流星.png'},
      {id:'gordon', n:'戈登高人团', t:'infantry', c:6, f:1, a:3, h:10, s:['guard'], d:'gordonPick', img:R+'英/戈登高人团.jpg'},
      {id:'grenadier', n:'掷弹兵卫队', t:'infantry', c:6, f:1, a:5, h:9, s:['guard'], img:R+'英/掷弹兵卫队.jpg'},
      {id:'spitfire2', n:'喷火 MkIIa', t:'fighter', c:4, f:2, a:4, h:4, d:'spitfireMk2'},
      {id:'blackprince', n:'A43 黑王子', t:'tank', c:5, f:2, a:3, h:6, s:['guard'], r:1, e:['frontMax2'], d:'avreRetreat', img:R+'英/A43 黑王子.png'},
      {id:'第85先锋连', n:'第85先锋连', c:1, t:'infantry', f:4, a:0, h:4, s:['smoke'], d:'第85先锋连'},
      {id:'亨伯MkIV', n:'亨伯MkIV', c:1, t:'tank', f:1, a:1, h:2, s:['fight','impact'], d:'亨伯MkIV'},
      {id:'威尔士卫队', n:'威尔士卫队', c:1, t:'infantry', f:1, a:1, h:2, s:['guard'], d:'威尔士卫队', target:'any'},
      {id:'角斗士Mkl', n:'角斗士Mkl', c:1, t:'fighter', f:1, a:1, h:3, d:'角斗士Mkl'},
      {id:'北极熊师', n:'北极熊师', c:2, t:'infantry', f:1, a:1, h:3, s:['coop','fight'], d:'北极熊师'},
      {id:'牛津', n:'牛津', c:2, t:'bomber', f:1, a:1, h:3, d:'牛津'},
      {id:'M3A3甜心', n:'M3A3甜心', c:2, t:'tank', f:1, a:2, h:3, d:'M3A3甜心'},
      {id:'柴郡团', n:'柴郡团', c:2, t:'infantry', f:1, a:0, h:5, d:'柴郡团'},
      {id:'第10突击队', n:'第10突击队', c:2, t:'infantry', f:1, a:2, h:1, s:['smoke'], d:'第10突击队'},
      {id:'P-40小鹰', n:'P-40小鹰', c:3, t:'fighter', f:2, a:2, h:3, d:'P-40小鹰', target:'enemy-army'},
      {id:'游骑兵营', n:'游骑兵营', c:3, t:'infantry', f:1, a:2, h:5, s:['fight'], d:'游骑兵营'},
      {id:'东萨里团', n:'东萨里团', c:3, t:'infantry', f:1, a:2, h:6, s:['guard'], d:'东萨里团'},
      {id:'布伦亨MkIV', n:'布伦亨MkIV', c:3, t:'bomber', f:2, a:2, h:3, d:'布伦亨MkIV'},
      {id:'瓦伦丁MkI', n:'瓦伦丁MkI', c:3, t:'tank', f:1, a:2, h:4, s:['fight'], d:'瓦伦丁MkI'},
      {id:'边防团', n:'边防团', c:3, t:'infantry', f:1, a:2, h:5, s:['fight'], d:'边防团'},
      {id:'皇家燧发枪团', n:'皇家燧发枪团', c:3, t:'infantry', f:3, a:0, h:8, s:['guard'], d:'皇家燧发枪团'},
      {id:'十字军Mkll', n:'十字军Mkll', c:3, t:'tank', f:1, a:2, h:3, d:'十字军Mkll'},
      {id:'血腥第十一团', n:'血腥第十一团', c:4, t:'infantry', f:1, a:4, h:5, d:'血腥第十一团'},
      {id:'玛蒂尔达MkV', n:'玛蒂尔达MkV', c:4, t:'tank', f:2, a:3, h:5, s:['impact'], r:1, d:'玛蒂尔达MkV'},
      {id:'司事火炮', n:'司事火炮', c:5, t:'artillery', f:2, a:3, h:4, d:'司事火炮', target:'enemy-unit'},
      {id:'黑卫士兵团', n:'黑卫士兵团', c:5, t:'infantry', f:1, a:2, h:6, s:['fight','guard'], d:'黑卫士兵团'},
      {id:'旋风', n:'旋风', c:6, t:'fighter', f:2, a:6, h:6, d:'旋风'},
      {id:'彗星A34', n:'彗星A34', c:6, t:'tank', f:2, a:6, h:6, r:1, d:'彗星A34'},
      {id:'英俊战士TFMkX', n:'英俊战士TFMkX', c:6, t:'fighter', f:2, a:4, h:4, d:'英俊战士TFMkX'},
      {id:'蚊式MkVⅥ', n:'蚊式MkVⅥ', c:6, t:'bomber', f:2, a:4, h:4, d:'蚊式MkVⅥ', target:'enemy-unit'},
      {id:'45英寸中型火炮', n:'45英寸中型火炮', c:6, t:'artillery', f:2, a:3, h:3, d:'45英寸中型火炮', target:'enemy-unit'},
      {id:'舍伍德森林人团', n:'舍伍德森林人团', c:6, t:'infantry', f:1, a:5, h:6, s:['guard'], d:'舍伍德森林人团', target:'any'},
      {id:'兰开斯特BII', n:'兰开斯特BII', c:7, t:'bomber', f:3, a:5, h:4, s:['blitz'], d:'兰开斯特BII'},
      {id:'威灵顿', n:'威灵顿', c:7, t:'bomber', f:3, a:4, h:3, s:['blitz'], d:'威灵顿'},
      {id:'92英寸岸防炮', n:'92英寸岸防炮', c:7, t:'artillery', f:2, a:3, h:6, d:'92英寸岸防炮'},
      {id:'暴风MkV', n:'暴风MkV', c:7, t:'fighter', f:2, a:3, h:7, s:['ambush'], d:'暴风MkV'},
      {id:'卡梅伦团', n:'卡梅伦团', c:7, t:'infantry', f:1, a:7, h:8, s:['guard'], d:'卡梅伦团'},
    ],
    orders:[
      {id:'fort', n:'防御工事', c:3, e:'fortify'},
      {id:'carpet', n:'地毯式轰炸', c:7, e:'carpetBomb'},
      {id:'desert', n:'沙漠之鼠', c:1, e:'desertRat', target:'enemy-unit'},
      {id:'monty', n:'蒙哥马利', c:1, e:'montgomery', target:'enemy-unit'},
      {id:'mx175', n:'MX 175 护航队', c:3, e:'draw2'},
      {id:'tea', n:'一杯茶', c:1, e:'tea', img:R+'英/一杯茶.jpg'},
      {id:'navalsupport', n:'海军支援', c:2, e:'navalSupport', target:'any', img:R+'英/海军支援.jpg'},
      {id:'commonwealth', n:'英联邦', c:12, e:'commonwealth', img:R+'英/英联邦.jpg'},
      {id:'precision', n:'精准轰炸', c:7, e:'precisionBomb', target:'enemy-unit', img:R+'英/精准轰炸.png'},
      {id:'eject', n:'驱逐', c:5, e:'eject', target:'enemy-unit'},
      {id:'totalwar', n:'全域战争', c:5, e:'totalWar'},
      {id:'engage', n:'逢敌', c:2, e:'suppressOne', target:'any', img:R+'英/逢敌.jpg'},
      {id:'climax', n:'高潮迭起', c:6, e:'climax', img:R+'英/高潮迭起.jpg'},
      {id:'landgirl', n:'土地女孩', c:2, e:'landGirl', s:['coop'], img:R+'英/土地女孩.jpg'},
      {id:'convoy', n:'护送航运', c:1, e:'convoy', img:R+'英/护送航运.jpg'},
      {id:'shortage', n:'物资短缺', c:3, e:'shortage', img:R+'英/物资短缺.jpg'},
      {id:'homeguard', n:'国土警卫队', c:1, e:'homeGuard', target:'any', s:['coop'], img:R+'英/国土警卫队.jpg'},
      {id:'dust', n:'沙尘满目', c:3, e:'dustStorm', target:'any', img:R+'英/沙尘满目.jpg'},
      {id:'monsoon', n:'季风侵袭', c:6, e:'monsoon', img:R+'英/季风侵袭.jpg'},
      {id:'observer', n:'前线观察员', c:4, e:'frontObserver', img:R+'英/前线观察员.jpg'},
      {id:'greetings', n:'诚挚问候', c:4, e:'greetings', img:R+'英/诚挚问候.png'},
      {id:'daybomb', n:'日间轰炸', c:4, e:'dayBomb', target:'any', img:R+'英/日间轰炸.png'},
      {id:'HMS塔尔伯特', n:'HMS塔尔伯特', c:1, e:'HMS塔尔伯特'},
      {id:'两难困境', n:'两难困境', c:1, e:'两难困境', target:'any'},
      {id:'坚决守护', n:'坚决守护', c:1, e:'坚决守护', target:'any'},
      {id:'袋鼠运输', n:'袋鼠运输', c:1, e:'袋鼠运输', target:'any'},
      {id:'观察团', n:'观察团', c:1, e:'观察团'},
      {id:'防空弹幕', n:'防空弹幕', c:1, e:'防空弹幕', target:'any'},
      {id:'战术撤退', n:'战术撤退', c:1, e:'战术撤退', target:'friendly-unit'},
      {id:'妇女预备队', n:'妇女预备队', c:1, e:'妇女预备队'},
      {id:'为了国王', n:'为了国王', c:2, e:'为了国王', target:'enemy-unit'},
      {id:'咬紧牙关', n:'咬紧牙关', c:2, e:'咬紧牙关'},
      {id:'拖延战术', n:'拖延战术', c:2, e:'拖延战术'},
      {id:'深沟固垒', n:'深沟固垒', c:2, e:'深沟固垒', target:'friendly-unit'},
      {id:'空投补给', n:'空投补给', c:2, e:'空投补给', target:'any'},
      {id:'最光辉的时刻', n:'最光辉的时刻', c:2, e:'最光辉的时刻', target:'any'},
      {id:'HMS光辉号', n:'HMS光辉号', c:3, e:'HMS光辉号'},
      {id:'军情五处', n:'军情五处', c:3, e:'军情五处'},
      {id:'炮击', n:'炮击', c:5, e:'炮击'},
      {id:'停飞', n:'停飞', c:5, e:'停飞', target:'any'},
      {id:'渗透', n:'渗透', c:5, e:'渗透'},
      {id:'突击队突击', n:'突击队突击', c:5, e:'突击队突击', target:'any'},
      {id:'参谋长联席会议', n:'参谋长联席会议', c:6, e:'参谋长联席会议'},
      {id:'HMS竞技神号', n:'HMS竞技神号', c:6, e:'HMS竞技神号'},
      {id:'合作关系', n:'合作关系', c:6, e:'合作关系'},
      {id:'战时盟国', n:'战时盟国', c:7, e:'战时盟国', target:'enemy-unit'},
      {id:'租借法案', n:'租借法案', c:7, e:'租借法案'},
      {id:'统治吧！不列颠尼亚！', n:'统治吧！不列颠尼亚！', c:8, e:'统治吧！不列颠尼亚！'},
      {id:'皇家研发', n:'皇家研发', c:3, e:'皇家研发'},
    ],
    counters:[
      {id:'firewatch', n:'国家消防局', c:2, e:'hqCap'},
      {id:'ultra', n:'ULTRA', c:3, e:'ultra', img:R+'英/ULTRA.jpg'},
      {id:'规避动作', n:'规避动作', c:0, e:'规避动作'},
      {id:'拦截', n:'拦截', c:1, e:'拦截'},
      {id:'第一响应', n:'第一响应', c:3, e:'第一响应'}
    ] },
  jp: { name:'日本', hq:'装饰/总部/日/特鲁克.png',
    units:[
      {id:'s7', n:'搜索第七联队', t:'infantry', c:1, f:1, a:2, h:1, s:['ambush','情报1'], e:['s7Death'], img:R+'日/搜索第七联队.jpg'},
      {id:'chihat', n:'三式中战车', t:'tank', c:5, f:2, a:5, h:5, e:['rowGuardAmbush'], img:R+'日/三式中战车.jpg'},
      {id:'osaka', n:'大版联队', t:'infantry', c:5, f:1, a:4, h:7, s:['guard'], img:R+'日/大版联队.jpg'},
      {id:'a6m2', n:'A6M2零战', t:'fighter', c:4, f:2, a:4, h:4, s:['ambush'], d:'dmgRand1', target:'any'},
      {id:'d3a', n:'D3A2九九舰爆', t:'bomber', c:3, f:2, a:3, h:2, s:['smoke'], e:['perAllyD3']},
      {id:'t93', n:'九三式装甲车', t:'tank', c:1, f:1, a:1, h:1, e:['auraAtk1']},
      {id:'r2', n:'第二挺进团', t:'infantry', c:3, f:1, a:2, h:2, s:['blitz'], d:'destroyAtk2', target:'enemy-unit'},
      {id:'sendai', n:'仙台联队', t:'infantry', c:4, f:1, a:2, h:3, s:['smoke'], d:'exile', target:'enemy-unit'},
      {id:'s33', n:'搜索第33联队', t:'infantry', c:1, f:1, a:1, h:2, e:['onDamagedDraw']},
      {id:'c15', n:'骑兵第15联队', t:'infantry', c:1, f:0, a:2, h:1, s:['blitz']},
      {id:'t41', n:'四一式山炮', t:'artillery', c:2, f:2, a:3, h:2, e:['noHq']},
      {id:'ki44', n:'Ki-44 二式战 钟馗', t:'fighter', c:4, f:2, a:4, h:2, s:['ambush'], d:'ki44Discard', img:R+'日/Ki-44 二式战 钟馗.jpg'},
      {id:'ki43', n:'Ki-43 一式战 隼', t:'fighter', c:4, f:2, a:4, h:3, e:['ki43Death'], img:R+'日/Ki-43 一式战 隼.jpg'},
      {id:'ki61', n:'Ki-61 三式战改 飞燕', t:'fighter', c:6, f:3, a:5, h:4, s:['blitz'], e:['ki61Auto'], img:R+'日/Ki-61 三式战改 飞燕.jpg'},
      {id:'n1k', n:'N1K-J紫电局地战', t:'fighter', c:5, f:3, a:4, h:4, s:['blitz','ambush','fight'], img:R+'日/N1K-J紫电局地战.jpg'},
      {id:'shinbata', n:'新发田联队', t:'infantry', c:1, f:1, a:1, h:3, e:['orderPunish'], img:R+'日/新发田联队.jpg'},
      {id:'ki84', n:'Ki-84 四式战 疾风', t:'fighter', c:5, f:3, a:7, h:5, s:['fight'], e:['noHq'], img:R+'日/Ki-84 四式战 疾风.jpg'},
      {id:'type94', n:'九四式轻装甲车', t:'tank', c:1, f:0, a:1, h:1, d:'type94', img:R+'日/九四式轻装甲车.png'},
      {id:'comm1', n:'通信第一联队', t:'infantry', c:1, f:4, a:0, h:4, s:['smoke'], e:['comm1'], img:R+'日/通信第一联队.png'},
      {id:'九二式重装甲车', n:'九二式重装甲车', c:1, t:'tank', f:0, a:1, h:2, s:['smoke'], d:'九二式重装甲车'},
      {id:'姬路联队', n:'姬路联队', c:1, t:'infantry', f:1, a:3, h:1, d:'姬路联队'},
      {id:'秋田联队', n:'秋田联队', c:2, t:'infantry', f:1, a:2, h:1, s:['blitz'], d:'秋田联队'},
      {id:'水户联队', n:'水户联队', c:3, t:'infantry', f:1, a:2, h:3, s:['blitz'], d:'水户联队'},
      {id:'京都联队', n:'京都联队', c:3, t:'infantry', f:1, a:2, h:4, s:['guard','情报1'], d:'京都联队'},
      {id:'熊本联队', n:'熊本联队', c:3, t:'infantry', f:0, a:4, h:1, s:['blitz'], d:'熊本联队'},
      {id:'Ki-61三式战飞燕', n:'Ki-61三式战飞燕', c:5, t:'fighter', f:3, a:5, h:4, s:['blitz'], d:'Ki-61三式战飞燕'},
      {id:'试制橘花', n:'试制橘花', c:7, t:'fighter', f:3, a:6, h:5, s:['blitz'], d:'试制橘花'},
      {id:'Ki-49百式重爆吞龙', n:'Ki-49百式重爆吞龙', c:9, t:'bomber', f:3, a:5, h:4, s:['blitz'], d:'Ki-49百式重爆吞龙'},
    ],
    orders:[
      {id:'amphib', n:'两栖进攻', c:3, e:'amphibious', target:'enemy-unit'},
      {id:'power', n:'火力爆发', c:1, e:'powerSurge', target:'friendly-fighter'},
      {id:'bomraid', n:'轰炸突袭', c:4, e:'bombRaid', target:'enemy-unit-hq'},
      {id:'yamamoto', n:'山本五十六', c:1, e:'yamamoto', img:R+'日/山本五十六.jpg'},
      {id:'rampage', n:'猛袭', c:2, e:'rampage', target:'enemy-infantry', img:R+'日/猛袭.jpg'},
      {id:'sword', n:'武士之刃', c:6, e:'killEnemy', target:'enemy-unit', img:R+'日/武士之刃.jpg'},
      {id:'southplan', n:'南进计划', c:4, e:'southPlan', img:R+'日/南进计划.jpg'},
      {id:'dawnop', n:'拂晓行动', c:2, e:'dawnOp', img:R+'日/拂晓行动.jpg'},
      {id:'blazing', n:'烈日', c:3, e:'blazing', img:R+'日/烈日.jpg'},
      {id:'backlight', n:'逆光攻击', c:2, e:'backlight', img:R+'日/逆光攻击.jpg'},
      {id:'lastjourney', n:'终焉之行', c:3, e:'lastJourney', img:R+'日/终焉之行.jpg'},
      {id:'quickwin', n:'快速胜利', c:1, e:'quickWin', target:'any', img:R+'日/快速胜利.jpg'},
      {id:'diplomat', n:'外交专员', c:1, e:'diplomat', target:'enemy-unit', img:R+'日/外交专员.jpg'},
      {id:'carrierwar', n:'航母战', c:3, e:'carrierWar', target:'any', img:R+'日/航母战.jpg'},
      {id:'tora', n:'虎！虎！虎！', c:2, e:'tora', img:R+'日/虎！虎！虎！.jpg'},
      {id:'lastresort', n:'亡命之计', c:2, e:'lastResort', img:R+'日/亡命之计.jpg'},
      {id:'empireforce', n:'帝国之力', c:1, e:'empireForce', img:R+'日/帝国之力.jpg'},
      {id:'edict', n:'天皇诏令', c:0, e:'edict', img:R+'日/天皇诏令.jpg'},
      {id:'lastpush', n:'最后一搏', c:10, e:'lastPush', img:R+'日/最后一搏.jpg'},
      {id:'homeland', n:'本土决战', c:8, e:'homelandDef', img:R+'日/本土决战.jpg'},
      {id:'fighttilend', n:'至死方休', c:10, e:'wipeAll', img:R+'日/至死方休.jpg'},
      {id:'longrange', n:'远距离交战', c:2, e:'longRange', target:'enemy-unit', img:R+'日/远距离交战.jpg'},
      {id:'sneak', n:'偷袭', c:1, e:'sneakAttack', target:'enemy-unit', img:R+'日/偷袭.png'},
      {id:'islanddef', n:'岛屿防御', c:4, e:'islandDef', img:R+'日/岛屿防御.png'},
      {id:'hakko', n:'八纮一宇', c:5, e:'hakkoIchiu', img:R+'日/八纮一宇.png'},
      {id:'调整', n:'调整', c:0, e:'调整'},
      {id:'帝国指令', n:'帝国指令', c:1, e:'帝国指令', target:'any'},
      {id:'扩张', n:'扩张', c:1, e:'扩张'},
      {id:'新式战法', n:'新式战法', c:1, e:'新式战法', target:'any'},
      {id:'极限使命', n:'极限使命', c:1, e:'极限使命', target:'friendly-unit'},
      {id:'责无旁贷', n:'责无旁贷', c:1, e:'责无旁贷', target:'friendly-unit'},
      {id:'为了天皇', n:'为了天皇', c:1, e:'为了天皇'},
      {id:'穷兵黩武', n:'穷兵黩武', c:2, e:'穷兵黩武', target:'any'},
      {id:'最后的仪式', n:'最后的仪式', c:3, e:'最后的仪式'},
      {id:'枪林弹雨', n:'枪林弹雨', c:3, e:'枪林弹雨', target:'enemy-unit'},
      {id:'玉碎', n:'玉碎', c:3, e:'玉碎', target:'friendly-unit'},
      {id:'指挥不当', n:'指挥不当', c:3, e:'指挥不当', target:'any'},
      {id:'侦察队', n:'侦察队', c:3, e:'侦察队'},
      {id:'暴风雨前的宁静', n:'暴风雨前的宁静', c:4, e:'暴风雨前的宁静'},
      {id:'帝国研发', n:'帝国研发', c:3, e:'帝国研发'},
    ],
    counters:[] },
  /* ============================================================
     盟国（只能作为盟国出战，不能选为主国；无总部场景素材）
     数据来源：卡牌/{波,法,芬,意}/文档.txt
     ============================================================ */
  pl: { name:'波兰', allyOnly:true, hq:null,
    units:[
      {id:'legion', n:'军团', t:'infantry', c:2, f:1, a:2, h:2, s:['guard'], e:['intelBuff']},
      {id:'tarnow', n:'塔尔努夫第16步兵团', t:'infantry', c:4, f:2, a:4, h:6, e:['intelLegion']},
      {id:'zaza', n:'扎扎师', t:'infantry', c:4, f:1, a:2, h:5, s:['blitz','fight'], e:['onDamagedDraw']},
      {id:'wolf15', n:'第15狼步兵团', t:'infantry', c:5, f:1, a:4, h:4, d:'routUnit', target:'any'}
    ],
    orders:[
      {id:'extendline', n:'延长战线', c:2, e:'extendLine'},
      {id:'punish', n:'严惩', c:2, e:'punish'},
      {id:'westplan', n:'西线计划', c:3, e:'westPlan'}
    ],
    counters:[] },
  fr: { name:'法国', allyOnly:true, hq:null,
    units:[
      {id:'expedition', n:'远征军', t:'infantry', c:2, f:2, a:2, h:2, d:'addResistance'}
    ],
    orders:[
      {id:'resistvive', n:'抵抗万岁!', c:1, e:'resistanceHail'},
      {id:'honorloyal', n:'荣誉与忠诚', c:2, e:'honorLoyalty', target:'any'},
      {id:'compromise', n:'妥协', c:3, e:'compromise'},
      {id:'deepdefense', n:'纵深防御', c:3, e:'deepDefense', target:'any'},
      {id:'callcolony', n:'呼叫殖民地', c:4, e:'callColony'},
      {id:'armedresist', n:'武装抵抗', c:4, e:'armedResistance'},
      {id:'phonywar', n:'假战', c:5, e:'phonyWar'},
      {id:'liberation', n:'解放', c:6, e:'liberation'},
      {id:'saar', n:'萨尔攻势', c:6, e:'saarOffensive', target:'any'},
      {id:'ruin', n:'毁坏', c:7, e:'ruinHand'},
      {id:'lorraine', n:'洛林十字', c:9, e:'lorraine', target:'enemy-any'},
      {id:'maginot', n:'马奇诺防线', c:3, e:'maginot', target:'friendly-army'}
    ],
    counters:[] },
  fi: { name:'芬兰', allyOnly:true, hq:null,
    units:[
      {id:'furT26', n:'T-26 FI', t:'tank', c:1, f:1, a:1, h:3, e:['vsStronger2']},
      {id:'finnboys', n:'芬兰男孩步兵团', t:'infantry', c:3, f:1, a:2, h:7, s:['guard'], e:['noDiscard']},
      {id:'bf109g', n:'Bf 109G 古斯塔夫 FI', t:'fighter', c:3, f:2, a:3, h:4, e:['mt208']},
      {id:'r13fi', n:'第13步兵团', t:'infantry', c:5, f:1, a:2, h:4, s:['guard'], d:'perEnemy11'}
    ],
    orders:[
      {id:'lotta', n:'洛塔组织', c:2, e:'lotta'},
      {id:'molotov', n:'莫洛托夫鸡尾酒', c:2, e:'molotov', target:'any'},
      {id:'whitedeath', n:'白色死神', c:4, e:'whiteDeath'},
      {id:'freeze', n:'强制冻结', c:4, e:'freeze', target:'friendly-unit'},
      {id:'longsiege', n:'长久围困', c:5, e:'longSiege'}
    ],
    counters:[
      {id:'frosttrap', n:'极寒陷阱', c:2, e:'frostTrap'},
      {id:'friendlyfire', n:'误伤', c:2, e:'friendlyFire'},
      {id:'sisu', n:'西苏精神', c:3, e:'sisuSpirit'}
    ] },
  it: { name:'意大利', allyOnly:true, hq:null,
    units:[
      {id:'cr42', n:'菲亚特 C.R.42', t:'fighter', c:1, f:1, a:1, h:2, d:'cr42Buff'},
      {id:'g50', n:'菲亚特 G.50', t:'fighter', c:2, f:2, a:2, h:3, e:['g50HqHeal']},
      {id:'mc200', n:'马基 C.200', t:'fighter', c:2, f:2, a:2, h:2, d:'perAllyAir11'},
      {id:'g55', n:'菲亚特 G.55', t:'fighter', c:4, f:2, a:4, h:4, d:'g55Buff'},
      {id:'mc205', n:'马基 C.205', t:'fighter', c:6, f:2, a:5, h:6, s:['blitz'], e:['vsAir2']},
      {id:'mas10', n:'第10快艇支队', t:'infantry', c:7, f:1, a:2, h:5, s:['ambush','guard'], d:'masKill'}
    ],
    orders:[
      {id:'colonialdream', n:'殖民梦', c:1, e:'colonialDream'},
      {id:'directstrike', n:'单刀直入', c:3, e:'directStrike', target:'enemy-unit'},
      {id:'steelpact', n:'钢铁条约', c:4, e:'steelPact'},
      {id:'attackcolony', n:'进攻殖民地', c:4, e:'attackColony', target:'enemy-any'},
      {id:'lionday', n:'一日之狮', c:4, e:'lionOfDay', target:'any'},
      {id:'navalbattle', n:'海军交战', c:9, e:'navalBattle'}
    ],
    counters:[] }
};


/* ---------- 老兵形态（不进卡池；与本体是同一张卡，满足条件后就地转换） ----------
   键 = 本体卡名；引擎 promoteToVeteran() 按此模板就地替换 def（换名/换数值/换词条/换卡图）。
   词条以《卡牌/{国}/文档.txt》「（老兵）」条目与本批数值表为准；老兵形态沿用本体 id（同一张卡）。
   部署效果 id（d）与本体保持一致：老兵形态仍是同一张卡，其效果文本不变；
   重复触发由 promoteToVeteran 的模板查找兜底（老兵名不在表内 → 不再转换）。 */
const VETERAN_FORMS = {
  '第119掷弹兵团': {id:'第119掷弹兵团', n:'第119掷弹兵团（老兵）', c:6, t:'infantry', f:2, a:6, h:6, s:['veteran','ambush','fight'], d:'第119掷弹兵团', e:['vetEnemyDebuff12'],
    desc:'友方回合结束时，使所有敌方单位获得-1-2', img:R+'德/第119掷弹兵团（老兵）.png'},   // 老兵形态效果按 卡牌/德/文档.txt（用户手补，勿覆盖）
  '第35掷弹兵团': {id:'第35掷弹兵团', n:'第35掷弹兵团（老兵）', c:6, t:'infantry', f:2, a:6, h:6, s:['veteran','ambush','blitz'], d:'第35掷弹兵团', e:['vetHqDmg4'],
    desc:'友方回合结束时，对敌方总部造成4点伤害', img:R+'德/第35掷弹兵团（老兵）.png'},   // 老兵形态效果按 卡牌/德/文档.txt（用户手补，勿覆盖）
  '四号坦克H型': {id:'四号坦克H型', n:'四号坦克H型（老兵）', c:7, t:'tank', f:2, a:5, h:5, s:['veteran'], d:'四号坦克H型', e:['vetBlitzAura4'],
    desc:'友方攻击力为4以上的陆军具有闪击', img:R+'德/四号坦克H型（老兵）.png'},   // 老兵形态效果按 卡牌/德/文档.txt（用户手补，勿覆盖）
  '近卫机械化第12旅': {id:'近卫机械化第12旅', n:'近卫机械化第12旅（老兵）', c:1, t:'infantry', f:1, a:2, h:2, s:['veteran','blitz'], d:'近卫机械化第12旅', e:['vetDraw2'],
    desc:'升为老兵时，抽2张牌', img:R+'苏/近卫机械化第12旅（老兵）.png'},   // 老兵形态效果按 卡牌/苏/文档.txt（用户手补，勿覆盖）
  '玛蒂尔达MkV': {id:'玛蒂尔达MkV', n:'玛蒂尔达MkV（老兵）', c:4, t:'tank', f:2, a:3, h:5, s:['veteran','impact'], r:1, d:'玛蒂尔达MkV', img:R+'英/玛蒂尔达MkV（老兵）.png'},   // 词条按 卡牌/英/文档.txt「（老兵）」条目：冲击、重甲1（与本体一致）
};

/* ---------- 稀有度（对齐《卡牌/{国}/文档.txt》：金/银/铜/铁；组卡上限 金1/银2/铜3/铁4） ---------- */
const RARITY_CAPS = { 金:1, 银:2, 铜:3, 铁:4 };
const RARITY = {
  /* 美 us */ b17:'银', p51:'铜', p40:'铁', m7:'铜', f4u:'铁', b25:'铜', m18:'银', sbd:'铜', r17:'铁', r506:'铁', t19:'铁',
  gunboat:'铁', deathfromabove:'铜', warmachine:'铁', missouri:'金', usarmyair:'金', warneed:'铜', warbond:'铜', aswpatrol:'铜', spot:'银',
  f4f:'铁', pb2y:'铜', aircover:'铁', carriergroup:'铜', carriercover:'铜', yorktown:'银',
  r32:'铁', r1def:'铜', reddevil:'银', r164:'铁', patton:'金', forfreedom:'银', quinine:'铜', eng109:'银', motivate:'铜',
  /* 德 de */ leopold:'金', pz2:'铁', pz35:'铜', r59:'铁', bf109:'铁', tiger:'银', r980:'铁', panzer3:'金', pz3j:'铜',
  eagleclaw:'铁', airstrike:'铜', bismarck:'金', tirpitz:'金', smalltalk:'铁',
  r20:'银', hs129:'银', r7:'银', blitzkrieg:'铜', coopop:'铁', bridge:'银',
  me163:'金', me262:'金', enigma:'银', buzzbomb:'铜', flashraid:'铜',
  ktiger:'金', warnavy:'金', wolfpack:'银',
  /* 苏 su */ r84:'铁', i16:'铁', r554:'铁', r89:'铁', t34:'铁', t70:'铁', su76:'铁', katyusha:'铜', il28:'铁', yak9:'银', partisan:'铜', r216:'铁', t3485:'金',
  burningsky:'铁', frompeople:'铁', winterwar:'铁', bloodsickle:'铁', gw:'金', winteroff:'金', mudseason:'铜', hammer:'铜', focus:'金',
  m503:'铜', r25:'铁', reserve:'铁', deepop:'铜', frontalassault:'铁', stz:'银', r75:'金',
  /* 英 gb */ r5:'铁', humber:'铁', churchill:'铁', lancaster:'铜', swordfish:'铁', spitfire:'铁', coldstream:'铜', lancashire:'铁',
  fort:'铁', carpet:'银', desertrat:'铁', monty:'金', mx175:'铁', tea:'铁', navalsupport:'铁', firewatch:'铁', cameron:'金',
  manchester:'金', stirling:'银', avre:'金', meteor:'金', gordon:'金', grenadier:'银',
  commonwealth:'金', precision:'铜', eject:'银', totalwar:'金', ultra:'金',
  stratbomb:'金',
  /* 日 jp */ a6m2:'铁', d3a:'铜', t93:'铜', r2:'金', sendai:'银', s33:'银', c15:'铜', t41:'银', ki44:'铜', ki43:'铁', ki61:'铜', n1k:'金',
  amphib:'铜', power:'银', bomraid:'金', yamamoto:'金', rampage:'铜', sword:'银', southplan:'银', dawnop:'铜', blazing:'铁', backlight:'银',
  shinbata:'铁', ki84:'铜', lastjourney:'银', quickwin:'金', diplomat:'铁', carrierwar:'金', tora:'铁', lastresort:'金', empireforce:'铁', edict:'铁',
  s7:'铁', chihat:'铜', osaka:'铁', lastpush:'金', homeland:'金', fighttilend:'金',
  stratbomb:'金', airdrop:'铁', wedge:'铜',
  westaf:'铁', ucarrier:'金', middlesex:'银', cmdo9:'铁', charmboy:'铁', cmdo46:'铁',
  engage:'银', climax:'金', landgirl:'铜', convoy:'铁', shortage:'铁', homeguard:'铁', dust:'金', monsoon:'铜', observer:'银',
  /* 新增（2026-09 文档） */
  comm593:'金', coerce:'铁', nightbomb:'金', highbomb:'金',
  gryphon:'金', pantherD:'金', rhodes:'铁', tigerE:'金', bp42:'金',
  ironore:'铁', guderian:'金', routcheap:'铁', inhibit:'铁', exploit:'金', alpine:'金', massrout:'金', fromdeep:'金',
  eng329:'金', holm99:'铁', p39:'银', roadberlin:'金', zhukov:'金', closecombat:'银', weigh:'铜', harshwinter:'金', tractorplant:'金', frontarmy:'金',
  spitfire2:'金', blackprince:'金', greetings:'金', daybomb:'银',
  type94:'铜', comm1:'金', longrange:'铜', sneak:'铁', islanddef:'铁', hakko:'铜',
  /* 盟国·波 pl */ tarnow:'银', zaza:'银', wolf15:'银', extendline:'铁', punish:'银', westplan:'铁',
  /* 盟国·法 fr */ expedition:'铁', resistvive:'铁', honorloyal:'铁', compromise:'铁', deepdefense:'铜', callcolony:'铜',
  armedresist:'银', phonywar:'银', liberation:'银', saar:'铜', ruin:'铜', lorraine:'银', maginot:'铜',
  /* 盟国·芬 fi */ furT26:'铁', finnboys:'银', bf109g:'铜', r13fi:'铁', lotta:'铜', molotov:'铜', whitedeath:'银',
  freeze:'铁', longsiege:'银', frosttrap:'银', friendlyfire:'铁', sisu:'铜',
  /* 盟国·意 it */ cr42:'铁', g50:'铜', mc200:'铁', g55:'铜', mc205:'银', mas10:'银',
  colonialdream:'铁', directstrike:'银', steelpact:'银', attackcolony:'银', lionday:'银', navalbattle:'银',
  '虎王': '金',
  '鼠式': '金',
  '第158补给营': '金',
  '三号坦克L型': '金',
  '38(t)坦克': '铁',
  '三号坦克H型': '银',
  '豹式坦克A型': '银',
  '第119掷弹兵团': '金',
  '第35掷弹兵团': '金',
  'Fw190A百舌鸟': '铁',
  '四号坦克H型': '铜',
  '俯冲轰炸': '铁',
  '转变攻击': '金',
  '第二战线': '铁',
  '交叉火力': '银',
  '斩草除根': '银',
  '大混战': '银',
  '德意志帝国研发': '金',
  '九二式重装甲车': '铁',
  '姬路联队': '铁',
  '秋田联队': '铁',
  '水户联队': '铁',
  '京都联队': '铜',
  '熊本联队': '铜',
  'Ki-61三式战飞燕': '铁',
  '试制橘花': '金',
  'Ki-49百式重爆吞龙': '金',
  '调整': '铁',
  '帝国指令': '铁',
  '扩张': '铁',
  '新式战法': '铁',
  '极限使命': '铁',
  '责无旁贷': '铁',
  '为了天皇': '银',
  '穷兵黩武': '银',
  '最后的仪式': '金',
  '枪林弹雨': '铁',
  '玉碎': '铁',
  '指挥不当': '铜',
  '侦察队': '银',
  '暴风雨前的宁静': '银',
  '帝国研发': '金',
  'M26潘兴': '金',
  '第142步兵团': '铁',
  '第5步兵团': '铁',
  '霹雳师': '金',
  '第175步兵团': '铁',
  '红牛师': '铁',
  'M10A1': '铜',
  'F7F虎猫': '金',
  'M6': '金',
  '超级堡垒B-29': '金',
  '陆军工程兵团': '铁',
  '战略规划': '金',
  '消耗战': '铁',
  '防火墙': '铁',
  '黑夜巡视': '铁',
  '战时美利坚': '铁',
  '星条旗': '铁',
  '我们能做到！': '铜',
  '同盟国': '银',
  '掩护部队': '铜',
  '爱国热忱': '银',
  '美国军事研发': '金',
  'IS-2': '金',
  '近卫机械化第12旅': '铁',
  '伊尔-10': '金',
  'SU-85': '铁',
  'BP-43装甲列车': '金',
  '近卫步兵第4团': '金',
  '背水一战': '铁',
  '最后一击': '铁',
  '暴风雪': '铜',
  '焦土政策': '铜',
  '以剑之名': '银',
  '胜利旗帜': '金',
  '苏联军事研发': '金',
  '第85先锋连': '金',
  '亨伯MkIV': '铁',
  '威尔士卫队': '铁',
  '角斗士Mkl': '铜',
  '北极熊师': '铁',
  '牛津': '金',
  'M3A3甜心': '铜',
  '柴郡团': '铜',
  '第10突击队': '铜',
  'P-40小鹰': '金',
  '游骑兵营': '金',
  '东萨里团': '铁',
  '布伦亨MkIV': '铁',
  '瓦伦丁MkI': '铁',
  '边防团': '铁',
  '皇家燧发枪团': '铜',
  '十字军Mkll': '银',
  '血腥第十一团': '铁',
  '玛蒂尔达MkV': '铜',
  '司事火炮': '金',
  '黑卫士兵团': '银',
  '旋风': '金',
  '彗星A34': '金',
  '英俊战士TFMkX': '金',
  '蚊式MkVⅥ': '金',
  '45英寸中型火炮': '铁',
  '舍伍德森林人团': '铁',
  '兰开斯特BII': '金',
  '威灵顿': '金',
  '92英寸岸防炮': '铜',
  '暴风MkV': '铜',
  '卡梅伦团': '银',
  'HMS塔尔伯特': '金',
  '两难困境': '铁',
  '坚决守护': '铁',
  '袋鼠运输': '铁',
  '观察团': '铁',
  '防空弹幕': '铁',
  '战术撤退': '铜',
  '妇女预备队': '铜',
  '为了国王': '铁',
  '咬紧牙关': '铁',
  '拖延战术': '铁',
  '深沟固垒': '铁',
  '空投补给': '铁',
  '最光辉的时刻': '银',
  'HMS光辉号': '金',
  '第一响应': '铁',
  '军情五处': '银',
  '炮击': '金',
  '停飞': '铁',
  '渗透': '铜',
  '突击队突击': '铜',
  '参谋长联席会议': '铁',
  'HMS竞技神号': '铜',
  '合作关系': '银',
  '战时盟国': '金',
  '租借法案': '铜',
  '统治吧！不列颠尼亚！': '金',
  '皇家研发': '金',
  '规避动作': '铁',
  '拦截': '铁',
};
const rarityOf = (id, dflt) => RARITY[id] || dflt || '铁';
const maxCopiesOf = (id) => RARITY_CAPS[rarityOf(id)];

/* ---------- 衍生卡（稀有度：无；不可直接加入卡组/不进图鉴——由其他卡效果生成） ----------
   F2A 水牛：F4F-4 野猫 / PB2Y卡罗纳多 / 空中掩护 / 航母打击群 / USS约克城号 的效果生成物
   轻步兵：预备役 / 大纵深作战 / 正面突击 / 步兵第25团 的生成物（可加入手牌） */
const DERIVED_CARDS = {
  f2a: { id:'f2a', n:'F2A 水牛', t:'fighter', c:1, f:1, a:1, h:2, e:['frontAtk1'], rarity:'无', img:'卡牌/美/F2A 水牛.jpg' },
  lightinf: { id:'lightinf', n:'轻步兵', t:'infantry', c:1, f:0, a:1, h:1, rarity:'无', img:'卡牌/苏/轻步兵.jpg' },
  garrison: { id:'garrison', n:'卫戍', t:'infantry', c:1, f:1, a:0, h:3, s:['guard'], e:['garrisonTick'], rarity:'无', img:'卡牌/英/卫戍.jpg' },
  /* 盟国衍生单位 */
  legion: { id:'legion', n:'军团', t:'infantry', c:2, f:1, a:2, h:2, s:['guard'], e:['intelBuff'], rarity:'衍生', img:'卡牌/波/军团.png' },
  rout:   { id:'rout', n:'溃军', t:'infantry', c:1, f:1, a:1, h:1, rarity:'衍生', img:'卡牌/中立/溃军.png' },
  guerrilla:{ id:'guerrilla', n:'游击队员', t:'infantry', c:1, f:1, a:1, h:1, e:['guerrillaKill'], rarity:'无', img:'卡牌/芬/游击队员.png' },
  'V-1飞行炸弹': { id:'V-1飞行炸弹', kind:'order', nation:'de', n:'V-1飞行炸弹', c:0, img:R+'德/V-1飞行炸弹.png', e:'V-1飞行炸弹', target:'any', desc:'消灭 1 个花费不大于 3 的单位'},
  '合成机油': { id:'合成机油', kind:'order', nation:'de', n:'合成机油', c:0, img:R+'德/合成机油.png', e:'合成机油', desc:'下个回合开始时,获得 10 个指挥点并抽 1 张牌'},
  'XXⅪ级U型潜艇': { id:'XXⅪ级U型潜艇', kind:'order', nation:'de', n:'XXⅪ级U型潜艇', c:0, img:R+'德/XXⅪ级U型潜艇.png', e:'XXⅪ级U型潜艇', target:'any', desc:'消灭 1 个单位,敌方随机弃 2 张牌'},
  '铀工程': { id:'铀工程', kind:'order', nation:'de', n:'铀工程', c:12, img:R+'德/铀工程.png', e:'铀工程', desc:'消灭所有敌方单位;每消灭 1 个单位,获得 1 个指挥点'},
  '扩展德意志帝国研发': { id:'扩展德意志帝国研发', kind:'order', nation:'de', n:'扩展德意志帝国研发', c:6, img:R+'德/扩展德意志帝国研发.png', e:'扩展德意志帝国研发', desc:'抉择:将 1 张「合成机油」或 1 张「高级德意志帝国研发」加入手牌'},
  '高级德意志帝国研发': { id:'高级德意志帝国研发', kind:'order', nation:'de', n:'高级德意志帝国研发', c:9, img:R+'德/高级德意志帝国研发.png', e:'高级德意志帝国研发', desc:'抉择:将 1 张「XXⅪ级U型潜艇」或 1 张「铀工程」加入手牌'},
  '神风特攻队': { id:'神风特攻队', kind:'order', nation:'jp', n:'神风特攻队', c:1, img:R+'日/神风特攻队.png', e:'神风特攻队', desc:'对敌方总部造成 1 点伤害,抽 1 张牌'},
  '氧气鱼雷': { id:'氧气鱼雷', kind:'order', nation:'jp', n:'氧气鱼雷', c:0, img:R+'日/氧气鱼雷.png', e:'氧气鱼雷', target:'any', desc:'消灭 1 个单位;若其攻击力不大于 3,抽 2 张牌'},
  '高级帝国研发': { id:'高级帝国研发', kind:'order', nation:'jp', n:'高级帝国研发', c:9, img:R+'日/高级帝国研发.png', e:'高级帝国研发', desc:'抉择:将 1 张「7075铝」或 1 张「皇国二号兵器」加入手中'},
  '皇国二号兵器': { id:'皇国二号兵器', kind:'order', nation:'jp', n:'皇国二号兵器', c:12, img:R+'日/皇国二号兵器.png', e:'皇国二号兵器', desc:'将 4 张「试制橘花」置于卡组顶;使其花费和行动花费为 0'},
  '气球炸弹': { id:'气球炸弹', kind:'order', nation:'jp', n:'气球炸弹', c:0, img:R+'日/气球炸弹.png', e:'气球炸弹', desc:'压制所有敌方单位'},
  '扩展帝国研发': { id:'扩展帝国研发', kind:'order', nation:'jp', n:'扩展帝国研发', c:6, img:R+'日/扩展帝国研发.png', e:'扩展帝国研发', desc:'抉择:将 1 张「氧气鱼雷」或 1 张「高级帝国研发」加入手中'},
  '7075铝': { id:'7075铝', kind:'order', nation:'jp', n:'7075铝', c:0, img:R+'日/7075铝.png', e:'7075铝', desc:'将 3 张「A6M2零战」加入手中,使其花费为 0,获得:"亡计:将 1 张本单位的复制加入手中,使其花费为 0"'},
  '加压舱': { id:'加压舱', kind:'order', nation:'us', n:'加压舱', c:0, img:R+'美/加压舱.png', e:'加压舱', desc:'将 1 张「B-29超级堡垒」加入手牌;随机消灭 1 个敌方单位'},
  '深水炸弹': { id:'深水炸弹', kind:'order', nation:'us', n:'深水炸弹', c:0, img:R+'美/深水炸弹.png', e:'深水炸弹', desc:'额外获得 1 个指挥点槽;使友方总部具有烟幕,直到下个友方回合开始'},
  '青霉素': { id:'青霉素', kind:'order', nation:'us', n:'青霉素', c:0, img:R+'美/青霉素.png', e:'青霉素', desc:'使所有友方单位和总部获得 +6 防御力,抽 4 张牌'},
  '扩展美国研发': { id:'扩展美国研发', kind:'order', nation:'us', n:'扩展美国研发', c:6, img:R+'美/扩展美国研发.png', e:'扩展美国研发', desc:'抉择:将 1 张「加压舱」或 1 张「高级美国研发」加入手牌'},
  '曼哈顿计划': { id:'曼哈顿计划', kind:'order', nation:'us', n:'曼哈顿计划', c:6, img:R+'美/曼哈顿计划.png', e:'曼哈顿计划', desc:'对所有敌方目标造成 6 点伤害'},
  '高级美国研发': { id:'高级美国研发', kind:'order', nation:'us', n:'高级美国研发', c:9, img:R+'美/高级美国研发.png', e:'高级美国研发', desc:'抉择:将 1 张「青霉素」或 2 张「曼哈顿计划」加入手牌'},
  '倾斜装甲': { id:'倾斜装甲', kind:'order', nation:'su', n:'倾斜装甲', c:0, img:R+'苏/倾斜装甲.png', e:'倾斜装甲', desc:'将 1 个「IS-2」加入支援阵线,使其与 1 个敌方单位战斗;回合结束时,将其返回手中'},
  '扩展苏联研发': { id:'扩展苏联研发', kind:'order', nation:'su', n:'扩展苏联研发', c:6, img:R+'苏/扩展苏联研发.png', e:'扩展苏联研发', desc:'抉择:将 1 张「标准弹药」或 1 张「高级苏联研发」加入手中'},
  '标准弹药': { id:'标准弹药', kind:'order', nation:'su', n:'标准弹药', c:0, img:R+'苏/标准弹药.png', e:'标准弹药', desc:'使手中和卡组中所有友方单位获得 -1 花费和 -1 行动花费'},
  '气动雪橇': { id:'气动雪橇', kind:'order', nation:'su', n:'气动雪橇', c:0, img:R+'苏/气动雪橇.png', e:'气动雪橇', target:'enemy-army', desc:'对 1 个敌方陆军或总部造成 2 点伤害,对其相邻目标造成 2 点伤害'},
  '高级苏联研发': { id:'高级苏联研发', kind:'order', nation:'su', n:'高级苏联研发', c:9, img:R+'苏/高级苏联研发.png', e:'高级苏联研发', desc:'抉择:将 1 张「倾斜装甲」或 3 张「斯大林管风琴」加入手中'},
  '斯大林管风琴': { id:'斯大林管风琴', kind:'order', nation:'su', n:'斯大林管风琴', c:4, img:R+'苏/斯大林管风琴.png', e:'斯大林管风琴', desc:'造成 8 点伤害,随机分配至所有敌方目标'},
  '合成橡胶': { id:'合成橡胶', kind:'order', nation:'gb', n:'合成橡胶', c:0, img:R+'英/合成橡胶.png', e:'合成橡胶', target:'any', desc:'使 1 个单位获得 +4 防御力,使其攻击力等同于其防御力'},
  '雷达': { id:'雷达', kind:'order', nation:'gb', n:'雷达', c:0, img:R+'英/雷达.png', e:'雷达', desc:'抽 1 张牌;使友方总部获得 +4 防御力'},
  '主动声呐': { id:'主动声呐', kind:'order', nation:'gb', n:'主动声呐', c:0, img:R+'英/主动声呐.png', e:'主动声呐', desc:'压制所有敌方单位,使对手手牌获得 +3 花费'},
  '布莱切利庄园': { id:'布莱切利庄园', kind:'order', nation:'gb', n:'布莱切利庄园', c:12, img:R+'英/布莱切利庄园.png', e:'布莱切利庄园', desc:'将敌方手中和场上所有花费不大于 5 的卡牌返回其卡组顶'},
  '扩展皇家研发': { id:'扩展皇家研发', kind:'order', nation:'gb', n:'扩展皇家研发', c:6, img:R+'英/扩展皇家研发.png', e:'扩展皇家研发', desc:'抉择:将 1 张「合成橡胶」或 1 张「高级皇家研发」加入手牌'},
  '高级皇家研发': { id:'高级皇家研发', kind:'order', nation:'gb', n:'高级皇家研发', c:9, img:R+'英/高级皇家研发.png', e:'高级皇家研发', desc:'抉择:将 1 张「主动声纳」或 1 张「布莱切利庄园」加入手牌'},
};
/* 衍生卡转完整单位定义（mkUnitDef 形状：atk/hp/blood/fuel——直接喂 spawnUnit/makeUnit；
   原始条目是 a/h/c/f 形状，直接透传会让单位数值变成 undefined） */
const makeDerived = (id) => {
  const d = DERIVED_CARDS[id];
  if(!d) return null;
  // 衍生「指令」（研发链那一批）：按指令卡形状返回，效果走 e → eff
  if(d.kind === 'order') return { kind:'order', id:d.id||id, n:d.n, blood:d.c, eff:d.e, target:d.target||null, nation:d.nation||null, rarity:d.rarity||'无', img:d.img, desc:d.desc||('花费 '+d.c) };
  return {
    kind:'unit', id:d.id, n:d.n, t:d.t,
    blood:d.c, fuel:d.f, atk:d.a, hp:d.h,
    sig:(d.s||[]).slice(), armor:d.r||0, fx:(d.e||[]).slice(),
    deploy:d.d||null, target:d.target||null, nation:d.nation||null,
    rarity:d.rarity||'无', img:d.img, desc:unitDesc(d)
  };
};
/* 特殊生成卡（如生产）：爆破——STZ-5喀秋莎 造成对战伤害时生成；对一个单位造成 1 点伤害（可砸双方单位） */
const BAOPO = { kind:'order', id:'baopo', n:'爆破', blood:0, eff:'baopo', target:'any', img:'卡牌/中立/爆破.jpg', desc:'对一个单位造成 1 点伤害' };
const makeBaopo = () => JSON.parse(JSON.stringify(BAOPO));
/* 中立特殊指令：计划（抽 1 张牌；通用载具可 -1 费并触发爆破；不入默认卡组，由效果加入手牌） */
const PLAN = { kind:'order', id:'plan', n:'计划', blood:2, eff:'plan', img:'卡牌/中立/计划.png', desc:'抽1张牌' };
const makePlan = () => JSON.parse(JSON.stringify(PLAN));
/* 盟国特殊生成卡：抵抗（法国，加入敌方手牌；抉择：对友方总部 1 点伤害 / 移除卡组顶 1 张牌） */
const RESIST = { kind:'order', id:'resist', n:'抵抗', blood:1, eff:'resistance', target:null, nation:'fr', img:'卡牌/法/抵抗.png',
  desc:'抉择:对友方总部造成1点伤害,或移除己方卡组顶的1张牌' };
const makeResist = () => JSON.parse(JSON.stringify(RESIST));

/* ---------- 描述 / 图片路径 ---------- */
function pathFor(key,name){ const dirs={us:'美',de:'德',su:'苏',gb:'英',jp:'日',pl:'波',fr:'法',fi:'芬',it:'意'}; return R + dirs[key] + '/' + name + '.png'; }
/* 按名称取原始卡定义（组卡器/战役自定义卡组用；返回浅拷贝，避免污染 NATIONS）。
   搜索顺序：单位 → 指令 → 反制；未命中返回 null。 */
function mkByName(key, name){
  const n = NATIONS[key];
  if(!n) return null;
  for(const list of [n.units, n.orders, n.counters]){
    for(const d of list){ if(d.n === name) return Object.assign({}, d); }
  }
  return null;
}
/* ---------- 单位效果文案（单一来源：卡面/图鉴/征程卡组查看共用） ---------- */
const UNIT_DEPLOY_TEXT = {
  '鼠式':'消灭花费小于4的单位,每有1个对1个敌方造成2点伤害',
  elimRand:'随机消灭 1 个敌方单位', dmgFlyRand5:'对 1 个敌方空军造成 5 点伤害',
  frontAlly11:'前线有友方单位时,获得 +1/+1', dmgRand3:'对 1 个随机敌方单位造成 3 点伤害',
  ally11:'使 1 个友方单位 +1/+1(目标可由你指定)', enemiesBack:'将所有敌方单位移回手牌',
  allyInfantryOil:'有友方步兵时,油费 -1', hqDmg2:'对友方总部造成 2 点伤害',  dmgRand1:'对任意 1 个单位(含友方)或敌方总部造成 1 点伤害', destroyAtk2:'消灭 1 个攻击力≤2 的敌方单位',
  exile:'将 1 个敌方单位移出战场(本单位离场时返回)',
  ki44Discard:'敌方随机弃掉手牌中 1 张轰炸机',
  coldstream:'将 1 张「海军支援」加入手牌',
  r32Copy:'部署:从卡组抽取 1 张「第32步兵团」',
  r1defBuff:'部署:若前线有友方美国单位,获得 +1 攻击力',
  r20Add:'部署:将 1 张「35（t）坦克」和 1 张「协同作战」加入手牌',
  hs129Fight:'部署:点选 1 个敌方单位,与其战斗',
  bounceTop:'部署:将 1 个敌方单位返回其所有者卡组顶',
  m503Buff:'部署:使所有友方「轻步兵」获得 +1/+1',
  me262Clear:'部署:消灭所有敌方空军',
  ktigerCrush:'部署:获得等同于敌方单位数的指挥点,消灭敌方所有陆军单位',
  manchesterPrec:'部署:将 1 张「精准轰炸」加入手牌',
  stirlingCarpet:'部署:将 1 张「地毯式轰炸」洗入卡组',
  avreRetreat:'部署:使所有敌方陆军撤退',
  gordonPick:'部署:点击手中的 1 张指令,使其花费为 0 并置于卡组顶',
  wafrica:'部署:抽取花费最低的指令;若是构筑之外的牌,重复此效果',
  middlesexAdd:'部署:将 1 张「卫戍」加入手牌',
  def1Pick:'部署:使 1 个敌方单位的防御力为 1',
  charmHq:'部署:使友方总部 +4 防御力',
  cmdo46Add:'部署:将 1 张「爆破」和 1 张「计划」加入手牌',
  /* 盟国（波/法/芬/意） */
  routUnit:'部署:将 1 个单位转换为「溃军」;若为友方单位,抽 2 张牌',
  addResistance:'部署:将 1 张「抵抗」加入敌方手牌',
  perEnemy11:'部署:每有 1 个敌方单位,获得一次 +1/+1',
  cr42Buff:'部署:若友方单位数多于敌方,获得 +1 攻击力',
  perAllyAir11:'部署:每有 1 个其他友方空军,获得一次 +1/+1',
  g55Buff:'部署:若友方总部比敌方总部防御力高 5 点或以上,获得 +2/+2',
  masKill:'部署:消灭敌方支援阵线 1 个单位',
  /* 新增（2026-09 文档） */
  bp42:'部署:将 2 个具有闪击的「第59装甲掷弹兵团」加入支援阵线',
  spitfireMk2:'部署:若有敌方空军,获得 +2/+2;否则获得奋战',
  holm99:'部署:下个友方回合开始时,失去 1 个指挥点',
  p39:'部署:随机消灭另 1 个友方单位',
  type94:'部署:将 1 张「偷袭」加入手牌',
  /* 追加（batch-E2 无标记纯光环/在手牌效果） */
  'M6':'每有 1 个攻击力不小于 4 的友方单位,友方总部受到的伤害 -1',
  'M3A3甜心':'友方抽 1 张牌时,使友方总部获得 +1 防御力',
  '近卫步兵第4团':'若在手中,敌方每抽 1 张牌,获得 -1 花费',
  'M26潘兴':'本单位在前线时,友方总部的防御力无法降为 1 以下',
  '第142步兵团':'本单位消灭 1 个敌方单位时,使友方总部获得 +2 防御力',
  '第5步兵团':'移至前线时,获得 +1/+1',
  '霹雳师':'抽 2 张牌;选择 1 张手牌并将其返回卡组顶',
  '第175步兵团':'选择 1 张手牌,将其返回卡组顶',
  '红牛师':'友方回合开始时,攻击力翻倍',
  'M10A1':'抑制 1 个敌方单位',
  'F7F虎猫':'友方回合结束时,将 1 个「SBD3无畏」加入支援阵线',
  '超级堡垒B-29':'造成 6 点伤害,随机分配至所有敌方目标',
  '虎王':'友方支援阵线卡牌无法成为敌方指令或部署的目标',
  '第158补给营':'友方回合中,消灭第一个敌方单位时,获得 2 个指挥点',
  '三号坦克L型':'友方单位每有一种非坦克类型,具有 +1 攻击力',
  '38(t)坦克':'抽 1 张牌',
  '三号坦克H型':'从卡组顶的 3 张牌中选择 1 张并抽取,将其余 2 张置于卡组底',
  '豹式坦克A型':'移至前线后,下个敌方回合开始时,敌方无法抽牌',
  '第119掷弹兵团':'若有友方「第35掷弹兵团」,升为老兵',
  '第35掷弹兵团':'若有友方「第119掷弹兵团」,升为老兵',
  'Fw190A百舌鸟':'抽 1 张牌',
  '四号坦克H型':'与 1 个敌方单位战斗,若将其消灭,升为老兵',
  'IS-2':'本单位被返回手中时,将 1 张复制加入支援阵线',
  '近卫机械化第12旅':'攻击力不小于 4 的友方坦克部署时,升为老兵',
  '伊尔-10':'亡计:将上 1 个被消灭的友方陆军加入支援阵线',
  'SU-85':'友方苏联坦克攻击时,使友方总部获得 +3 防御力',
  'BP-43装甲列车':'无法攻击;友方回合结束时,将 1 张「轻步兵」加入同一阵线',
  '第85先锋连':'每回合,友方使用的第一张指令具有 -1 花费',
  '威尔士卫队':'使 1 个目标获得 +1 防御力',
  '北极熊师':'上回合友方每部署过 1 个英国步兵,获得一次 +1/+1',
  '牛津':'陆军部署时,使其攻击力等同于其防御力',
  '柴郡团':'友方回合开始时,若上回合没有被攻击,对敌方总部造成 2 点伤害',
  '第10突击队':'友方使用指令时,随机对 1 个敌方目标造成 1 点伤害',
  'P-40小鹰':'对 1 个敌方陆军或总部造成 2 点伤害',
  '游骑兵营':'友方单位造成的非对战、非攻击伤害 +1',
  '边防团':'将 1 个「卫戍」加入支援阵线',
  '皇家燧发枪团':'友方使用指令时,将本单位的攻击力和行动花费交换',
  '十字军Mkll':'友方使用英国指令时,抽 1 张牌',
  '血腥第十一团':'本单位对战并存活后,获得 +2/+2',
  '玛蒂尔达MkV':'本单位冲击后,升为老兵',
  '司事火炮':'压制 1 个敌方单位;友方回合开始时,再次将其压制',
  '黑卫士兵团':'敌方指令具有 +2 花费',
  '旋风':'敌方指向或攻击本单位时,对其总部造成 3 点伤害',
  '彗星A34':'本单位对敌方总部造成伤害时,抽 1 张牌',
  '英俊战士TFMkX':'其他单位攻击本单位时,先对其造成 3 点伤害',
  '蚊式MkVⅥ':'对 1 个敌方单位造成 3 点伤害',
  '45英寸中型火炮':'压制 1 个敌方单位',
  '舍伍德森林人团':'将 1 个单位的复制返回其所有者卡组顶',
  '兰开斯特BII':'本单位对总部造成伤害时,使敌方手牌获得 +1 花费',
  '威灵顿':'若在手牌中,友方使用指令时,获得 -2 花费',
  '92英寸岸防炮':'本单位造成伤害时,使友方总部获得同等防御力',
  '暴风MkV':'敌方回合中,具有 +4 攻击力',
  '卡梅伦团':'每回合,友方使用第二张指令时,抽 2 张牌',
  '九二式重装甲车':'本单位对敌方总部造成伤害后,获得 +1 攻击力',
  '秋田联队':'亡计:随机对 1 个敌方目标造成 2 点伤害',
  '水户联队':'亡计:对敌方总部造成 2 点伤害',
  '京都联队':'移除 1 个敌方单位,直到本单位离开战场',
  '试制橘花':'亡计:将 4 张「神风特攻队」洗入卡组',
  'Ki-49百式重爆吞龙':'亡计:消灭所有单位',
};
const UNIT_FX_TEXT = {
  vsArmy3:'对陆军(步兵/坦克/炮兵)攻击 +3', vsTank2x:'对坦克攻击 ×2',
  moveNattack:'可移动并攻击', immuneSuppress:'免疫压制',
  chanceExtra1:'攻击有 50% 概率 +1 伤害', overflowHq:'击杀溢出伤害转移至敌方总部',
  deathDraw:'亡计:抽 1 张苏联牌', onDamagedDraw:'受伤时抽 1 张牌',
  auraAtk1:'在场时其他友方单位攻击 +1', perAllyD3:'每有 1 个其他友方 D3A2 九九舰爆,攻击 +2',
  noHq:'无法攻击敌方总部',
  ki43Death:'亡计:对敌方总部造成 2 点伤害',
  ki61Auto:'敌方回合结束时,若你有 7 点指挥点,自动消耗 7 点部署到己方底线',
  t19GuardBreak:'被本单位攻击的单位失去守护,直到回合结束',
  partisan:'亡计:对本回合所有对本单位造成过伤害的单位造成 3 点伤害',
  guard216:'友方回合开始时,对友方总部造成 2 点伤害,抽 1 张牌;第二次触发后升为老兵',
  panzer:'每次行动(移动或攻击都算)后,按本局已行动次数获得等量攻击力、防御力与油费',
  inhibitImmune:'无法被抑制',
  keepImpact:'不会失去冲击',
  /* 盟国（波/法/芬/意） */
  intelBuff:'友方使用情报牌时,获得 +1/+1',
  intelLegion:'友方使用情报牌时,将 1 张「军团」加入支援阵线并抽 1 张牌',
  vsStronger2:'对战攻击力更高的单位时,具有 +2 攻击力',
  noDiscard:'友方手牌无法被弃掉',
  mt208:'攻击敌方总部时,从敌方卡组抽 1 张牌;回合结束时将其弃掉',
  g50HqHeal:'本单位造成伤害时,使友方总部获得同等防御力',
  vsAir2:'对战空军时,具有 +2 攻击力',
  guerrillaKill:'消灭受到本单位对战伤害的单位',
  /* 新增（2026-09 文档） */
  hqDmgReduce1:'友方总部受到的伤害 -1',
  gryphon:'其他友方坦克具有 -1 行动花费',
  pantherD:'本单位攻击时,造成的伤害也会施加到敌方总部',
  rhodesCost:'在手牌中:每次友方反制触发时,获得 -2 花费',
  tigerE:'无法成为敌方指令的目标',
  eng329:'1 个其他友方单位被消灭时,使友方总部获得 +2 防御力',
  comm1:'1 个其他友方单位被消灭时,对敌方总部造成 1 点伤害',
  frontMax2:'前线至多有 2 个单位',
  f4fBuff:'移至前线时,将1个「F2A 水牛」加入相邻处',
  pb2yAura:'友方战斗机具有+1攻击力',
  frontAtk1:'在前线时,具有+1攻击力',
  reddevil:'敌方指向或攻击本单位时,+1花费',
  r164Death:'亡计:随机使 1 个友方单位获得 +1/+1',
  hs129Atk:'对抗陆军和总部时,具有 +2 攻击力',
  r7Vet:'本单位攻击并消灭 1 个单位时,升为老兵',
  eng109:'其他友方单位移至前线时,使其获得 +1 攻击力',
  r25Spawn:'友方回合结束时,将 1 个「轻步兵」加入同一战线',
  me163Back:'友方回合结束时,将本单位返回手牌',
  orderPunish:'敌方使用指令时,对其总部造成1点伤害',
  stzGen:'本单位造成对战伤害时,将等量的「爆破」加入手牌',
  r75Copy:'被敌方效果指向时,将1个复制加入友方总部相邻处',
  meteorAfter:'攻击后:移除本单位,将1张按当前数值翻倍的复制洗入卡组',
  s7Death:'亡计:若敌方手中有明牌,抽1张牌',
  rowGuardAmbush:'在支援战线时,具有伏击和守护',
  garrisonTick:'友方回合开始时,若上回合没有被攻击,对敌方总部造成1点伤害',
  ucarrierAura:'友方「计划」花费-1;友方使用「计划」时,将1张「爆破」加入手牌',
  /* 追加（batch-E2 触发/光环类标记） */
  f7fEnd:'友方回合结束时,将 1 个「SBD 3 无畏」加入支援阵线',
  is2Back:'本单位被返回手中时,将 1 张复制加入支援阵线',
  su85Aura:'友方苏联坦克攻击时,使友方总部获得 +3 防御力',
  firstOrderMinus1:'每回合,友方使用的第一张指令具有 -1 花费',
  pantherA:'移至前线后,下个敌方回合开始时,敌方无法抽牌',
  selfBurnTurn:'侵蚀:单位所有者回合开始时,对本单位造成1点伤害',
  'vsHq3':'对敌方总部攻击 +3',
  'drawReveal':'将 1 个「F2A 水牛」加入支援战线',
  r5Buff:'移至前线时,获得 +1/+1',
  vetTank12:'攻击力不小于 4 的友方坦克部署时,升为老兵',
  cheshireTick:'友方回合开始时,若上回合没有被攻击,对敌方总部造成 2 点伤害',
  commandoOrder:'友方使用指令时,随机对 1 个敌方目标造成 1 点伤害',
  rangerAura:'友方单位造成的非对战、非攻击伤害 +1',
  fusilierSwap:'友方使用指令时,将本单位的攻击力和行动花费交换',
  crusaderDraw:'友方使用英国指令时,抽 1 张牌',
  bloody11Fight:'本单位对战并存活后,获得 +2/+2',
  vetMatilda:'本单位冲击后,升为老兵',
  blackwatchTax:'敌方指令具有 +2 花费',
  whirlwindAura:'敌方指向或攻击本单位时,对其总部造成 3 点伤害',
  cometDraw:'本单位对敌方总部造成伤害时,抽 1 张牌',
  beaufighterPre:'其他单位攻击本单位时,先对其造成 3 点伤害',
  lancasterTax:'本单位对总部造成伤害时,使敌方手牌获得 +1 花费',
  x92HqHeal:'本单位造成伤害时,使友方总部获得同等防御力',
  stormAtk4FoeTurn:'敌方回合中,具有 +4 攻击力',
  cameron2ndOrder:'每回合,友方使用第二张指令时,抽 2 张牌',
};
/* 触发/光环类单位（applyDeploy 只挂标记、效果在钩子里）：卡面不加「部署:」前缀 */
const PASSIVE_UNITS = new Set(['第5步兵团', 'F7F虎猫', 'M6', '豹式坦克A型', 'IS-2', '近卫机械化第12旅', 'SU-85', 'BP-43装甲列车', '近卫步兵第4团', '第85先锋连', '牛津', 'M3A3甜心', '柴郡团', '第10突击队', '游骑兵营', '皇家燧发枪团', '十字军Mkll', '血腥第十一团', '玛蒂尔达MkV', '黑卫士兵团', '旋风', '彗星A34', '英俊战士TFMkX', '兰开斯特BII', '威灵顿', '92英寸岸防炮', '暴风MkV', '卡梅伦团']);
function unitDesc(u){
  const parts = [TYPEINFO[u.t], (u.c||0)+'费', (u.f||0)+'油'];
  if(u.s && u.s.length) parts.push(u.s.map(s=>SIGINFO[s]?SIGINFO[s].n:s).join('·'));
  if(u.r) parts.push('重甲'+u.r);
  if(u.d && UNIT_DEPLOY_TEXT[u.d]) parts.push(((typeof PASSIVE_UNITS !== 'undefined' && PASSIVE_UNITS.has(u.n)) || /^(部署:|亡计:)/.test(UNIT_DEPLOY_TEXT[u.d]) ? '' : '部署:') + UNIT_DEPLOY_TEXT[u.d]);
  if(u.e && u.e.length) parts.push(u.e.map(f=>UNIT_FX_TEXT[f]||f).join('；'));
  return parts.join('，');
}
function orderDesc(o){
  const map = {
    gunboat:'对敌方支援阵线1个单位或敌方总部造成2点伤害，使友方总部+2血量',
    deathFromAbove:'随机消灭1个敌方单位',
    warMachine:'额外获得1个指挥点槽',
    eagleClaw:'对敌方支援阵线所有单位造成2点伤害',
    airStrike:'对1个总部造成3点伤害',
    bismarck:'对1个总部造成8点伤害',
    burningSky:'对1个敌方空军造成4点伤害',
    fromPeople:'对1个单位造成3点伤害',
    winterWar:'对所有目标造成1点伤害',
    winterOffensive:'对所有目标造成4点伤害',
    bloodSickle:'对1个单位和友方总部造成1点伤害，抽1张牌',
    greatWar:'使双方总部的防御力为12',
    fortify:'友方总部获得+7防御力',
    carpetBomb:'对所有敌方单位造成3点伤害',
    desertRat:'对1个敌方单位造成1点伤害，将其压制',
    montgomery:'压制1个单位和其相邻单位，抽1张牌',
    mx175:'抽2张牌',
    amphibious:'消灭1个攻击力不大于3的敌方单位',
    powerSurge:'使1个友方战斗机具有+1攻击力和奋战，直到回合结束',
    bombRaid:'对1个目标造成3点伤害，对其相邻目标造成2点伤害；或指向敌方总部并随机对敌方底线2个单位造成2点伤害',
    tirpitz:'对敌方总部造成4点伤害,下个敌方回合中敌方无法部署单位',
    yamamoto:'本回合所有友方空军+1攻击力和闪击',
    missouri:'消灭前线1个单位,其相邻单位撤退',
    tea:'使所有场上友方英国单位获得+2防御力',
    navalSupport:'使1个单位的攻击力等同于其防御力',
    rampage:'消灭1个敌方步兵;若其攻击力大于你的指挥点槽数,失去1个指挥点槽',
    mudSeason:'对所有单位造成等同于其行动花费的伤害',
    usArmyAir:'抽1张美国轰炸机和1张美国战斗机',
    killEnemy:'消灭1个敌方单位',
    hammer:'对1个敌方陆军造成6点伤害',
    warNeed:'额外获得2个指挥点槽',
    warBond:'额外获得2个指挥点槽;下个友方回合开始时,额外抽1张牌',
    aswPatrol:'额外获得3个指挥点槽,随机消灭1个敌方单位',
    southPlan:'额外获得1个指挥点槽,敌方失去1个指挥点槽',
    airCover:'将2个「F2A 水牛」加入战场,若可能加入前线',
    carrierGroup:'抽取:抽1张空军;使所有友方空军获得+1/+1',
    carrierCover:'抉择:使所有友方战斗机获得+1/+1(抉择1)或移至前线(抉择2)',
    yorktown:'将4个「F2A 水牛」加入战场,若可能加入前线',
    dawnOp:'本回合友方空军行动花费为0,失去1个指挥点槽',
    blazing:'本回合所有友方空军+3攻击力',
    backlight:'本回合友方空军行动花费-1;若本回合已使用「烈日」,友方空军再+2攻击力',
    patton:'本回合,手牌中所有单位部署花费-1,部署后具有闪击',
    forFreedom:'使1个友方单位获得+1/+1,抽1张牌',
    quinine:'使1个友方步兵获得+1/+2和-1行动花费',
    blitzKrieg:'使前线所有友方单位获得+3攻击力和-1行动花费,直到回合结束',
    coopOp:'友方每有一种单位类型,使1个友方坦克获得一次+1/+1',
    motivate:'使1个友方单位获得等同于其行动花费的攻击力和防御力,使其行动花费为0',
    bridgeTooFar:'敌方回合结束时,若可能,将1个「三号坦克J型」加入前线;否则消灭前线所有单位',
    strategicFocus:'抉择:对所有陆军(抉择1)或空军(抉择2)造成5点伤害',
    reserve:'将2张「轻步兵」加入手牌;此前每使用过1张「预备役」,额外加入1张',
    deepOp:'将2张「轻步兵」加入手牌,将手牌中的「轻步兵」获得闪击',
    frontalAssault:'使所有友方「轻步兵」获得+1/+2;若没有「轻步兵」,将2张「轻步兵」加入手牌',
    enigma:'抽数张牌,直到友方手牌数与敌方相同',
    buzzBomb:'对1个敌方目标造成1点伤害;若目标是敌方总部,抽1张牌',
    lastJourney:'移除卡组顶的1张空军,造成等同于其攻击力的伤害,随机分配至所有敌方目标',
    quickWin:'造成3点伤害(可指任意单位或敌方总部),使敌方卡组中所有敌方单位获得+3攻击力',
    diplomat:'对1个敌方目标造成1点伤害;此前每使用过1张「外交专员」,伤害+1',
    carrierWar:'对敌方总部造成3点伤害,将「航母战」加入敌方手牌(数值+1)',
    tora:'对所有敌方目标造成1点伤害',
    lastResort:'对所有敌方目标造成2点伤害,友方失去1个指挥点槽',
    empireForce:'弃掉双方所有激活的反制,对敌方总部造成2点伤害',
    edict:'使本回合下个友方伤害指令造成的伤害+1',
    baopo:'对一个单位造成1点伤害',
    warNavy:'对敌方总部造成等同于其手牌数的伤害,敌方随机弃1张牌',
    wolfPack:'将1个单位返回其手牌(目标手牌已满则被摧毁),敌方随机弃1张牌',
    stratBomb:'对敌方支援战线所有目标造成3点伤害,同时打击敌方总部;敌方失去1个指挥点槽',
    commonwealth:'若友方总部防御力不小于30，对1个总部造成20点伤害(可指向己方或敌方);条件不足时仅抽4张牌',
    precisionBomb:'花费降低等同于友方轰炸机最高攻击力(最低0);消灭1个敌方单位',
    eject:'将1个敌方单位返回其卡组顶;抽己方卡组顶的1张牌,若为空军则部署(回合结束返回并洗入卡组)',
    totalWar:'友方空军部署时,获得+1攻击力和闪击',
    lastPush:'消灭所有单位,双方失去6个指挥点槽,双方卡组中的单位+3攻击力',
    homelandDef:'友方总部防御力不大于10时,花费为4;将「三式中战车」和「D3A2九九舰爆」加入支援战线',
    wipeAll:'消灭所有单位',
    paraDrop:'将数个「第506空降步兵团」加入支援战线直到已满;使其获得闪击和冲击',
    armorWedge:'使1个友方坦克和其相邻单位+1/+1',
    suppressOne:'压制1个单位,抽1张牌',
    climax:'对所有敌方单位造成2点伤害;若是本回合使用的第2张指令,改为造成4点伤害',
    landGirl:'协力,抽2张牌',
    convoy:'将1张「生产」和1张「计划」加入手牌',
    shortage:'使所有敌方单位获得:本单位所有者回合开始时,对本单位造成1点伤害',
    homeGuard:'协力,对1个单位造成2点伤害;将1张「卫戍」加入手牌',
    dustStorm:'压制1个单位,将2张「卫戍」加入支援战线',
    monsoon:'使所有敌方单位的防御力为1',
    frontObserver:'对所有敌方单位造成2点伤害;若上回合友方部署过英国步兵,抽1张牌',
    plan:'抽1张牌',
    /* 盟国·波 */
    extendLine:'将 1 张「军团」加入支援阵线,并触发等同于友方「军团」数量的情报',
    punish:'敌方随机弃 1 张牌;若弃掉的是明牌,友方抽 1 张牌',
    westPlan:'将 2 张「军团」加入支援阵线',
    /* 盟国·法 */
    resistance:'抉择:对友方总部造成 1 点伤害,或移除己方卡组顶的 1 张牌',
    resistanceHail:'将 1 张「抵抗」加入敌方手牌,抽 1 张牌',
    honorLoyalty:'将目标单位洗入其所有者的卡组;其所有者抽 2 张牌',
    compromise:'抉择:抽 1 张牌且友方总部 +3 防御力,或双方玩家各把该效果进行 2 次(各抽 2 张牌、双方总部各 +6 防御力)',
    deepDefense:'对 1 个单位造成等同于敌方手牌数的伤害',
    callColony:'抉择:使友方总部 +8 防御力,或抽 2 张牌',
    armedResistance:'将 1 张「抵抗」加入敌方手牌,并使敌方手牌中「抵抗」的数量与花费翻倍',
    phonyWar:'双方抽牌,直到手牌数为 8',
    liberation:'将 3 张「抵抗」加入敌方手牌;使友方总部获得等同于敌方手牌数的防御力',
    saarOffensive:'对 1 个单位造成 7 点伤害;若是本回合使用的第 1 张指令,将 1 张「洛林十字」加入手牌',
    ruinHand:'从敌方 3 张手牌中选择 1 张弃掉,并将 1 张复制加入友方手牌',
    lorraine:'敌方每有 1 张手牌,花费 -1;对 1 个敌方目标造成 3 点伤害',
    maginot:'使 1 个友方陆军获得 +3/+4,且无法撤退或被抑制',
    /* 盟国·芬 */
    lotta:'使所有友方单位获得 +1 防御力和 -1 行动花费',
    molotov:'对 1 个单位造成 2 点伤害;敌方随机弃 1 张牌;友方回合结束时弃掉此牌',
    whiteDeath:'抑制所有敌方单位;将 1 张具有闪击的「游击队员」加入支援阵线',
    freeze:'将 1 张「游击队员」加入 1 个友方单位相邻处,使其获得闪击和收缴',
    longSiege:'抽 4 张牌;下个友方回合结束时将其弃掉',
    /* 盟国·意 */
    colonialDream:'手牌中单位数最多的玩家抽 2 张牌',
    directStrike:'压制 1 个单位;若其具有唯一最高的攻击力,将其消灭',
    steelPact:'双方各抽 1 张牌,弃掉花费更低的那张,重复 3 次',
    attackColony:'对 1 个敌方目标造成 3 点伤害,并使友方总部 +5 防御力',
    lionOfDay:'消灭 1 个攻击力不小于 4 的单位',
    navalBattle:'完全修复友方支援阵线的所有单位;消灭敌方支援阵线的所有单位',
    /* 新增（2026-09 文档） */
    coerce:'抑制 1 个单位',
    nightBomb:'消灭 1 个未受伤单位,并随机排列所有敌方单位',
    highBomb:'随机消灭 2 个敌方单位',
    ironOre:'若前线有友方单位,获得 3 个指挥点',
    guderian:'使前线所有友方德国坦克获得 +2/+1',
    routCheap:'将 1 个花费不大于 2 的单位转换为「溃军」',
    inhibitOne:'抑制 1 个单位;若有友方空军,抽 1 张牌',
    exploitGain:'若前线有友方单位,从卡组顶 3 张单位中选择 1 张,使其获得闪击且花费为 0,其余 2 张置于卡组底',
    alpineFort:'使友方总部的防御力为 25;从卡组顶移除 10 张牌',
    massRout:'将所有敌方单位转换为「溃军」',
    roadBerlin:'使敌方总部获得:每回合累计受到的伤害不小于 3 时,使友方总部获得 +3 防御力',
    zhukov:'抽 1 张苏联步兵,使其部署时获得 +1/+1 和闪击',
    closeCombat:'使所有友方步兵具有 +3 攻击力,直到回合结束',
    weighOptions:'抽 2 张牌,选择并弃 1 张牌',
    harshWinter:'移除所有单位,将等量「轻步兵」加入同一阵线',
    tractorPlant:'将 2 个「T-34 1942」加入支援阵线',
    frontArmy:'使友方总部获得:友方回合开始时受到 1 点伤害,将 1 个「T-34 1942」加入支援阵线,回合结束时将其消灭',
    greetings:'使友方总部获得 +6 防御力,抽 2 张牌',
    dayBomb:'对 1 个目标造成 2 点伤害,敌方失去 1 个指挥点槽',
    longRange:'对 1 个敌方目标造成 2 点伤害',
    sneakAttack:'压制 1 个敌方单位;若其已被压制,将其消灭',
    islandDef:'若友方总部防御力不大于 10,抽 1 张牌;使友方总部获得 +6 防御力',
    hakkoIchiu:'抽 2 张牌;本局每失去过 1 个指挥点槽,获得 2 个指挥点',
    俯冲轰炸:'对 1 个敌方单位造成 1 点伤害;使其攻击力为 0,直到下个友方回合开始',
    转变攻击:'将 1 个友方单位返回其所有者手中;使其花费为 0,直到回合结束',
    第二战线:'移除 1 个友方单位;下个敌方回合结束时,将其返回并复制',
    交叉火力:'对所有敌方单位造成 1 点伤害;若有单位被消灭,重复此效果',
    斩草除根:'使所有单位获得 -1/-2',
    大混战:'对所有非老兵单位造成 4 点伤害',
    '陆军工程兵团':'使 1 个坦克或步兵获得 +1/+1',
    '战略规划':'将所有友方单位的攻击力和防御力翻倍',
    '消耗战':'对 1 个单位造成 2 点伤害;若是老兵,使其撤退',
    '防火墙':'使 1 个单位获得:"无法攻击敌方总部"',
    '黑夜巡视':'抽 2 张牌;选择 1 张手牌并将其返回卡组顶',
    '战时美利坚':'额外获得 1 个指挥点槽;若剩余指挥点数不小于 2,抽 1 张牌',
    '星条旗':'对敌方支援阵线所有单位造成等同于该阵线单位数的伤害',
    '我们能做到！':'所有友方单位和总部获得 +3 防御力,抽 1 张牌',
    '同盟国':'使所有友方非美国单位获得 +2/+2',
    '掩护部队':'每有 1 个友方「F2A水牛」,具有 -1 花费;将 2 个「SBD3无畏」加入支援阵线,使其获得闪击',
    '爱国热忱':'将 1 个友方单位的攻击力和防御力翻倍',
    '美国军事研发':'抉择:将 1 张「深水炸弹」或 1 张「扩展美国研发」加入手牌',
    '德意志帝国研发':'抉择:将 1 张「V-1飞行炸弹」或 1 张「扩展德意志帝国研发」加入手牌',
    '背水一战':'使 1 个单位获得:"无法撤退或被抑制"',
    '最后一击':'使 1 个友方单位获得 +3 攻击力;友方回合结束时,将其消灭',
    '暴风雪':'使所有单位的行动花费为 4,直到下个友方回合开始',
    '焦土政策':'使所有单位的行动花费为 4',
    '以剑之名':'抽取等同于敌方单位数的卡牌',
    '胜利旗帜':'指向 1 个单位;将其所有者的所有单位转换为此单位',
    '苏联军事研发':'抉择:将 1 张「气动雪橇」或 1 张「扩展苏联研发」加入手中',
    'HMS塔尔伯特':'友方总部即将受到致命伤害时,先获得 +6 防御力',
    '两难困境':'将 1 个单位的攻击力和行动花费交换',
    '坚决守护':'使 1 个守护单位获得 +1/+3',
    '袋鼠运输':'使 1 个英国步兵获得闪击和 +1 重甲;使其也算作是坦克',
    '观察团':'选择 1 张花费不小于 5 的手牌,使其获得 -2 花费',
    '防空弹幕':'使 1 个空军撤退,使友方总部获得 +2 防御力',
    '战术撤退':'使前线 1 个友方单位撤退,将其完全修复;本回合可再次操作此单位',
    '妇女预备队':'抉择:抽取卡组顶的单位,或使其获得伏击和冲击',
    '为了国王':'对 1 个敌方坦克造成 5 点伤害',
    '咬紧牙关':'抽 1 张牌;若有友方守护单位,额外抽 1 张牌',
    '拖延战术':'使前线所有单位撤退',
    '深沟固垒':'使 1 个友方守护单位获得 +3 攻击力、奋战和收缴',
    '空投补给':'使 1 个坦克或步兵获得 +4 防御力和守护,失去烟幕',
    '最光辉的时刻':'使 1 个空军获得 +1/+1 和闪击',
    'HMS光辉号':'将 2 个「剑鱼MkI」加入支援阵线,使其获得闪击',
    '军情五处':'敌方随机将 1 张手牌放回卡组顶,友方抽 1 张牌',
    '炮击':'压制所有敌方单位,对其造成 1 点伤害;敌方失去 1 个指挥点槽',
    '停飞':'将 1 个单位返回其所有者卡组顶',
    '渗透':'每个友方突击队随机对 1 个敌方目标造成等同于敌方明牌数的伤害',
    '突击队突击':'造成 1 点伤害;将 2 个「第10突击队」加入支援阵线',
    '参谋长联席会议':'使所有友方英国和美国单位获得 +2/+3',
    'HMS竞技神号':'将数个「剑鱼MkI」加入支援阵线,直到已满',
    '合作关系':'随机将 1 个美国精英单位加入支援阵线',
    '战时盟国':'将 1 个敌方单位洗入友方卡组',
    '租借法案':'抽 4 张牌',
    '统治吧！不列颠尼亚！':'使所有友方英国单位获得 +2 防御力,使其攻击力等同于其防御力',
    '皇家研发':'抉择:将 1 张「雷达」或 1 张「扩展皇家研发」加入手牌',
    '调整':'选择 1 张手牌洗入卡组,抽 1 张牌',
    '帝国指令':'完全修复 1 个单位,使其获得 +1/+1',
    '扩张':'若前线有友方日本单位,抽 2 张牌',
    '新式战法':'使 1 个单位忽略"无法攻击敌方总部"',
    '极限使命':'消灭 1 个友方单位,抽 2 张牌',
    '责无旁贷':'使 1 个友方单位获得 +1/+1;此前每使用过 1 张「责无旁贷」,额外获得一次 +1/+1',
    '为了天皇':'使所有友方日本单位具有 +1 攻击力和 -1 行动花费,直到回合结束',
    '穷兵黩武':'消灭 1 个攻击力不大于友方指挥点槽数的单位;失去 1 个指挥点槽',
    '最后的仪式':'将 8 张「神风特攻队」洗入卡组',
    '枪林弹雨':'对 1 个敌方单位和其相邻目标造成 1 点伤害;压制受到此伤害的单位',
    '玉碎':'使 1 个友方单位获得 +4/+4;回合结束时,将其消灭',
    '指挥不当':'消灭 1 个攻击力小于防御力的单位',
    '侦察队':'将 2 个「搜索第三十三联队」加入支援阵线',
    '暴风雨前的宁静':'使所有友方单位获得 +3/+1,结束回合',
    '帝国研发':'抉择:将 1 张「气球炸弹」或 1 张「扩展帝国研发」加入手中',
    'V-1飞行炸弹':'消灭 1 个花费不大于 3 的单位',
    '合成机油':'下个回合开始时,获得 10 个指挥点并抽 1 张牌',
    'XXⅪ级U型潜艇':'消灭 1 个单位,敌方随机弃 2 张牌',
    '铀工程':'消灭所有敌方单位;每消灭 1 个单位,获得 1 个指挥点',
    '扩展德意志帝国研发':'抉择:将 1 张「合成机油」或 1 张「高级德意志帝国研发」加入手牌',
    '高级德意志帝国研发':'抉择:将 1 张「XXⅪ级U型潜艇」或 1 张「铀工程」加入手牌',
    '神风特攻队':'对敌方总部造成 1 点伤害,抽 1 张牌',
    '氧气鱼雷':'消灭 1 个单位;若其攻击力不大于 3,抽 2 张牌',
    '高级帝国研发':'抉择:将 1 张「7075铝」或 1 张「皇国二号兵器」加入手中',
    '皇国二号兵器':'将 4 张「试制橘花」置于卡组顶;使其花费和行动花费为 0',
    '气球炸弹':'压制所有敌方单位',
    '扩展帝国研发':'抉择:将 1 张「氧气鱼雷」或 1 张「高级帝国研发」加入手中',
    '7075铝':'将 3 张「A6M2零战」加入手中,使其花费为 0,获得:"亡计:将 1 张本单位的复制加入手中,使其花费为 0"',
    '加压舱':'将 1 张「B-29超级堡垒」加入手牌;随机消灭 1 个敌方单位',
    '深水炸弹':'额外获得 1 个指挥点槽;使友方总部具有烟幕,直到下个友方回合开始',
    '青霉素':'使所有友方单位和总部获得 +6 防御力,抽 4 张牌',
    '扩展美国研发':'抉择:将 1 张「加压舱」或 1 张「高级美国研发」加入手牌',
    '曼哈顿计划':'对所有敌方目标造成 6 点伤害',
    '高级美国研发':'抉择:将 1 张「青霉素」或 2 张「曼哈顿计划」加入手牌',
    '倾斜装甲':'将 1 个「IS-2」加入支援阵线,使其与 1 个敌方单位战斗;回合结束时,将其返回手中',
    '扩展苏联研发':'抉择:将 1 张「标准弹药」或 1 张「高级苏联研发」加入手中',
    '标准弹药':'使手中和卡组中所有友方单位获得 -1 花费和 -1 行动花费',
    '气动雪橇':'对 1 个敌方陆军或总部造成 2 点伤害,对其相邻目标造成 2 点伤害',
    '高级苏联研发':'抉择:将 1 张「倾斜装甲」或 3 张「斯大林管风琴」加入手中',
    '斯大林管风琴':'造成 8 点伤害,随机分配至所有敌方目标',
    '合成橡胶':'使 1 个单位获得 +4 防御力,使其攻击力等同于其防御力',
    '雷达':'抽 1 张牌;使友方总部获得 +4 防御力',
    '主动声呐':'压制所有敌方单位,使对手手牌获得 +3 花费',
    '布莱切利庄园':'将敌方手中和场上所有花费不大于 5 的卡牌返回其卡组顶',
    '扩展皇家研发':'抉择:将 1 张「合成橡胶」或 1 张「高级皇家研发」加入手牌',
    '高级皇家研发':'抉择:将 1 张「主动声纳」或 1 张「布莱切利庄园」加入手牌',
    draw2:'抽 2 张牌',
  };
  return map[o.e] || '';
}
function counterDesc(o){
  const map = {
    spotEnemy:'敌方占领前线时，抽3张牌',
    enemyDeployDmg:'敌方单位部署时，对其造成3点伤害',
    hqCap:'敌方攻击我方总部时，伤害至多 1（触发后消失）',
    enemyDrawPunish:'敌方额外抽1张牌时，对其总部造成4点伤害',
    ultra:'敌方使用指令时，将其反制并抽1张牌',
    /* 盟国 */
    frostTrap:'敌方单位攻击时，加入 1 张「游击队员」并使其成为攻击目标',
    friendlyFire:'敌方单位攻击时，随机将攻击伤害转移至 1 个其他敌方目标',
    sisuSpirit:'友方总部受到伤害时，改为由敌方总部承受',
    fromDeep:'敌方单位部署时，将其消灭',
    '规避动作':'敌方部署单位时,反制其部署',
    '拦截':'敌方指令指向友方目标时,将其反制',
    '第一响应':'敌方回合结束时,将 1 个「第5步兵旅」加入支援阵线;若敌方单位数不小于 3,使其获得 +3/+3',
  };
  return map[o.e] || '';
}

/* ---------- 备用手绘精灵（无卡图时的 12×12 像素画） ---------- */
const ART = { squirrel:{c:{b:'#9a6a35',l:'#c99a5e',w:'#fff',k:'#2a1808'},r:[
    "....bbbb....", "...bbbbbb...", "..bbbbbbbb..", "..bbbbbbbb..",
    ".bbbbbbbb...", ".bbbbbbb....", "..bbbb......", "..bwbb......",
    ".bwwbbb.....", "bbbbbbb.....", "bbb.bbb.....", "b...b......."]} };
function padRow(s){ return (s||'').padEnd(12,'.'); }
function drawSprite(canvas, id){
  const a = ART[id] || ART.squirrel;
  const g = canvas.getContext('2d');
  g.clearRect(0, 0, canvas.width, canvas.height);
  const s = Math.floor(Math.min(canvas.width, canvas.height) / 12);
  const ox = Math.floor((canvas.width - 12*s)/2), oy = Math.floor((canvas.height - 12*s)/2);
  for(let y=0; y<12; y++){
    const row = padRow(a.r[y]);
    for(let x=0; x<12; x++){
      const c = row[x];
      if(c==='.' || c===' ') continue;
      g.fillStyle = a.c[c] || '#fff';
      g.fillRect(ox + x*s, oy + y*s, s, s);
    }
  }
}

const AI_DIFFS = [
  { v:'recruit', n:'新兵',    d:'偶尔失误的狼崽:每步决策 20% 概率出错' },
  { v:'veteran', n:'老练',    d:'战场老兵:保留白板、不做亏本交换' },
  { v:'warder',  n:'老牧师',  d:'教堂之主:先布反制、模拟交换、斩杀计算' },
  { v:'marshal', n:'元帅',    d:'最高统帅:拖回合保血量、优先出最强单位、最优顺序斩杀,不留机会' }
];
const VARIANTS = {
  v_sendai_fog:       { base:'jp:sendai', name:'仙台联队·雾夜', mods:{atk:3,hp:4}, source:{level:'c2', label:'战役·关二「雾之海峡」'}, note:'较原卡 2/3 烟幕步兵 +1/+1' },
  v_b17_early:        { base:'us:b17', name:'B-17飞行堡垒·晨曦', mods:{blood:6}, source:{level:'c3', label:'战役·关三「钢铁之雨」'}, note:'较原卡部署花费 8→6' },
  v_churchill_bulwark:{ base:'gb:churchill', name:'丘吉尔·巨壁', mods:{atk:3,hp:8}, source:{level:'c4', label:'战役·关四「永不沉没的堤岸」'}, note:'较原卡 2/7 守护·重甲1 +1/+1' },
  v_t34_winter:       { base:'su:t34', name:'T-34 1942·雪原', mods:{atk:6,hp:6}, source:{level:'c5', label:'战役·关五「燃烧的冬日」'}, note:'较原卡 5/5 闪击 +1/+1' }
};
/* 组卡规则：20–40 张 / 无单位数量限制（0 单位可行）/ 同名卡上限按稀有度（金1/银2/铜3/铁4）
   盟国机制：主国+盟国双国家卡池，自适应收紧 */
const DECK_RULES = {
  totalMin: 20, totalMax: 40, minUnits: 0, slots: 3
};
function poolCap(key){ const n = NATIONS[key]; const sum = l => l.reduce((s,x)=>s+maxCopiesOf(x.id),0); return sum(n.units) + sum(n.orders) + sum(n.counters); }
function unitCap(key){ const n = NATIONS[key]; return n.units.reduce((s,u)=>s+maxCopiesOf(u.id),0); }

/* ---------- 最终 Boss「hana」专用卡（用户 2026-09-16 拍板）----------
   **不放进 NATIONS**：不进正常卡池、不进图鉴、组卡器与 buildDeck 都看不到它们，
   只有 hana 第三条命的那一手会用到（在 Boss 脚本里加入手牌）。
   卡面来自桌面\DIY卡 的两张成品图（复制到 卡牌/中立/ 供内嵌）。 */
const BOSS_CARDS = {
  SUPERMAN: {
    id:'SUPERMAN', kind:'unit', n:'SUPERMAN', nation:'us', t:'infantry',
    c:0, f:1, a:9, h:5, s:['blitz','fight'], e:['moveNattack','orderDmgPlus1'], d:'SUPERMAN',
    rarity:'金', img:'卡牌/JM/SUPERMAN.jpg',
    desc:'闪击，奋战。本单位能在同一回合内移动并攻击。友方指令造成的伤害+1。部署：将敌方三张手牌转换为「轻步兵」'
  },
  SUPERTANK: {
    id:'SUPERTANK', kind:'unit', n:'SUPERTANK', nation:'us', t:'tank',
    c:2, f:1, a:2, h:3, s:['smoke'], e:['vsTank2x','infiniteFrontline'],
    rarity:'金', img:'卡牌/JM/SUPERTANK.jpg',
    desc:'烟幕。对战坦克时，具有双倍攻击力。本单位处于前线时，可以在同一回合攻击无限次'
  }
};

/* Node 导出（浏览器下跳过，靠全局变量） */
if (typeof module !== 'undefined') module.exports = {
  VETERAN_FORMS,
  NATIONS, SIGINFO, TYPEINFO, ART, drawSprite,
  pathFor, unitDesc, orderDesc, counterDesc, mkByName,
  UNIT_DEPLOY_TEXT, UNIT_FX_TEXT,
  RARITY, RARITY_CAPS, rarityOf, maxCopiesOf,
  DERIVED_CARDS, makeDerived, BAOPO, makeBaopo, PLAN, makePlan, RESIST, makeResist,
  AI_DIFFS, VARIANTS, DECK_RULES,
  poolCap, unitCap,
  BOSS_CARDS,
};
